CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY (
  ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
  NAME TEXT NOT NULL UNIQUE CHECK(LENGTH(NAME) BETWEEN 3 AND 255),
  PORT INTEGER NOT NULL UNIQUE CHECK(PORT BETWEEN 1025 AND 65535),
  STATUS TEXT NOT NULL DEFAULT 'active' CHECK(STATUS IN ('active', 'disabled')),
  UPSTREAM_URL TEXT NOT NULL CHECK(UPSTREAM_URL LIKE 'http%' AND LENGTH(UPSTREAM_URL) <= 2048),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY_AUTH_CONFIG (
  REGISTRY_ID TEXT NOT NULL,
  AUTH_TYPE TEXT NOT NULL DEFAULT 'anonymous' CHECK(AUTH_TYPE IN ('anonymous', 'basic', 'bearer')),
  CREDENTIAL_JSON BLOB,
  TOKEN_ENDPOINT TEXT,
  CERTIFICATE BLOB, 
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  UNIQUE(REGISTRY_ID)
);

CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG(
  REGISTRY_ID TEXT NOT NULL,
  PROXY_ENABLED INTEGER NOT NULL DEFAULT 0 CHECK(PROXY_ENABLED IN (0, 1)),
  PROXY_URL TEXT,
  CONNECTION_TIMEOUT INTEGER NOT NULL DEFAULT 10 CHECK(CONNECTION_TIMEOUT BETWEEN 1 AND 300),
  READ_TIMEOUT INTEGER NOT NULL DEFAULT 30 CHECK(READ_TIMEOUT BETWEEN 1 AND 600),
  MAX_CONNECTIONS INTEGER NOT NULL DEFAULT 100 CHECK(MAX_CONNECTIONS BETWEEN 1 AND 1000),
  MAX_RETRIES INTEGER NOT NULL DEFAULT 3 CHECK(MAX_RETRIES BETWEEN 0 AND 10),
  RETRY_DELAY INTEGER NOT NULL DEFAULT 5 CHECK(RETRY_DELAY BETWEEN 1 AND 60), 
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  UNIQUE(REGISTRY_ID),
  CHECK (
    (PROXY_ENABLED = 0) OR 
    (PROXY_ENABLED = 1 AND PROXY_URL IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG(
  REGISTRY_ID TEXT NOT NULL,
  STORAGE_LIMIT REAL DEFAULT 100 CHECK(STORAGE_LIMIT >= 100), -- min 100MB
  CLEANUP_POLICY TEXT NOT NULL DEFAULT 'lru_1m' CHECK(CLEANUP_POLICY IN ('lru_1m', 'lru_3m', 'lp')), -- LP = LEAST PULLED
  CLEANUP_THRESHOLD_PERCENTAGE REAL NOT NULL DEFAULT 80.0 CHECK(
  CLEANUP_THRESHOLD_PERCENTAGE BETWEEN 10.0 AND 95.0
  ),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  UNIQUE(REGISTRY_ID)
);

CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY_CACHE_CONFIG(
  REGISTRY_ID TEXT NOT NULL,
  TTL_SECONDS INTEGER NOT NULL DEFAULT 2592000 CHECK(TTL_SECONDS BETWEEN 600 AND 31536000), -- 10 mins to 1 year
  OFFLINE_MODE INTEGER NOT NULL DEFAULT 1 CHECK(OFFLINE_MODE IN (0, 1)), -- Changed from BOOLEAN to INTEGER
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  UNIQUE(REGISTRY_ID)
);


-- Triggers to automatically update UPDATED_AT timestamp
CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_auth_config_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY_AUTH_CONFIG
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY_AUTH_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE REGISTRY_ID = NEW.REGISTRY_ID;
END;

CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_access_config_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE REGISTRY_ID = NEW.REGISTRY_ID;
END;

CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_storage_config_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE REGISTRY_ID = NEW.REGISTRY_ID;
END;

CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_cache_config_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY_CACHE_CONFIG
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY_CACHE_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE REGISTRY_ID = NEW.REGISTRY_ID;
END;

------ tables for docker registry -----
CREATE TABLE IF NOT EXISTS REGISTRY_NAMESPACE(
  REGISTRY_ID TEXT NOT NULL,
  NAMESPACE TEXT NOT NULL,
  ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(REGISTRY_ID, NAMESPACE),
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_registry_namespace_updated_at
  AFTER UPDATE ON REGISTRY_NAMESPACE
BEGIN
  UPDATE REGISTRY_NAMESPACE SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;


CREATE TABLE IF NOT EXISTS REGISTRY_REPOSITORY(
  ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
  NAME TEXT NOT NULL,
  DESCRIPTION TEXT,
  NAMESPACE_ID TEXT NOT NULL,
  REGISTRY_ID TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (REGISTRY_ID, NAMESPACE_ID, NAME),
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  FOREIGN KEY (NAMESPACE_ID) REFERENCES REGISTRY_NAMESPACE(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_registry_repository_updated_at
  AFTER UPDATE ON REGISTRY_REPOSITORY
BEGIN
  UPDATE REGISTRY_REPOSITORY SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

CREATE TABLE IF NOT EXISTS IMAGE_BLOB_UPLOAD_SESSION (
  NAMESPACE_ID TEXT NOT NULL,
  REGISTRY_ID TEXT NOT NULL,
  REPOSITORY_ID TEXT NOT NULL,
  SESSION_ID TEXT PRIMARY KEY,
  BLOB_DIGEST TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IS_CHUNKED INTEGER CHECK (IS_CHUNKED IN (0, 1)), -- 0=MONOLITHIC, 1=CHUNKED
  UNIQUE(REGISTRY_ID, NAMESPACE_ID, BLOB_DIGEST),
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  FOREIGN KEY (NAMESPACE_ID) REFERENCES REGISTRY_NAMESPACE(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_image_blob_upload_session_updated_at
  AFTER UPDATE ON IMAGE_BLOB_UPLOAD_SESSION
BEGIN
  UPDATE IMAGE_BLOB_UPLOAD_SESSION SET UPDATED_AT = CURRENT_TIMESTAMP WHERE SESSION_ID = NEW.SESSION_ID;
END;

CREATE TABLE IF NOT EXISTS IMAGE_BLOB_META (
  NAMESPACE_ID TEXT NOT NULL,
  REGISTRY_ID TEXT NOT NULL,
  REPOSITORY_ID TEXT NOT NULL,
  BLOB_DIGEST TEXT NOT NULL,
  SIZE INTEGER NOT NULL,
  STORAGE_LOCATION TEXT NOT NULL UNIQUE,
  MEDIA_TYPE TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, BLOB_DIGEST),
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  FOREIGN KEY (NAMESPACE_ID) REFERENCES REGISTRY_NAMESPACE(ID) ON DELETE CASCADE,
  FOREIGN KEY (REPOSITORY_ID) REFERENCES REGISTRY_REPOSITORY(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_image_blob_meta_updated_at
  AFTER UPDATE ON IMAGE_BLOB_META
BEGIN
  UPDATE IMAGE_BLOB_META SET UPDATED_AT = CURRENT_TIMESTAMP 
  WHERE BLOB_DIGEST = NEW.BLOB_DIGEST AND REGISTRY_ID = NEW.REGISTRY_ID AND NAMESPACE_ID = NEW.NAMESPACE_ID;
END;

CREATE TABLE IF NOT EXISTS IMAGE_TAG(
  NAMESPACE_ID TEXT NOT NULL,
  REGISTRY_ID TEXT NOT NULL,
  REPOSITORY_ID TEXT NOT NULL,
  ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
  TAG TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (REGISTRY_ID,NAMESPACE_ID, REPOSITORY_ID, TAG),
  FOREIGN KEY (REPOSITORY_ID) REFERENCES REGISTRY_REPOSITORY(ID) ON DELETE CASCADE,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  FOREIGN KEY (NAMESPACE_ID) REFERENCES REGISTRY_NAMESPACE(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_image_tag_updated_at
  AFTER UPDATE ON IMAGE_TAG
BEGIN
  UPDATE IMAGE_TAG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

CREATE TABLE IF NOT EXISTS IMAGE_TAG_CONFIG_MAPPING(
  TAG_ID TEXT NOT NULL,
  CONFIG_DIGEST TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(TAG_ID, CONFIG_DIGEST),
  FOREIGN KEY (TAG_ID) REFERENCES IMAGE_TAG(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_image_tag_config_mapping_updated_at
  AFTER UPDATE ON IMAGE_TAG_CONFIG_MAPPING
BEGIN
  UPDATE IMAGE_TAG_CONFIG_MAPPING SET UPDATED_AT = CURRENT_TIMESTAMP 
  WHERE TAG_ID = NEW.TAG_ID AND CONFIG_DIGEST = NEW.CONFIG_DIGEST;
END;

CREATE TABLE IF NOT EXISTS IMAGE_PLATFORM_CONFIG (
  ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
  CONFIG_DIGEST TEXT NOT NULL,
  TAG_ID TEXT NOT NULL,
  NAMESPACE_ID TEXT NOT NULL,
  REGISTRY_ID TEXT NOT NULL,
  REPOSITORY_ID TEXT NOT NULL,
  OS TEXT NOT NULL,
  ARCH TEXT NOT NULL,
  PROPERTIES BLOB, -- JSON OBJECT OF PROPERTIES
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (TAG_ID, CONFIG_DIGEST),
  FOREIGN KEY (REPOSITORY_ID) REFERENCES REGISTRY_REPOSITORY(ID) ON DELETE CASCADE,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  FOREIGN KEY (NAMESPACE_ID) REFERENCES REGISTRY_NAMESPACE(ID) ON DELETE CASCADE,
  FOREIGN KEY (TAG_ID) REFERENCES IMAGE_TAG(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_image_platform_config_updated_at
  AFTER UPDATE ON IMAGE_PLATFORM_CONFIG
BEGIN
  UPDATE IMAGE_PLATFORM_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

CREATE TABLE IF NOT EXISTS IMAGE_LAYER_TAG_MAPPING (
  ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
  TAG_ID TEXT NOT NULL,
  IMAGE_CONFIG_DIGEST TEXT NOT NULL,
  LAYER_DIGEST TEXT NOT NULL,
  LAYER_INDEX INTEGER NOT NULL,
  NAMESPACE_ID TEXT NOT NULL,
  REGISTRY_ID TEXT NOT NULL,
  REPOSITORY_ID TEXT NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (TAG_ID, LAYER_DIGEST, LAYER_INDEX),
  FOREIGN KEY (REPOSITORY_ID) REFERENCES REGISTRY_REPOSITORY(ID) ON DELETE CASCADE,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  FOREIGN KEY (NAMESPACE_ID) REFERENCES REGISTRY_NAMESPACE(ID) ON DELETE CASCADE,
  FOREIGN KEY (TAG_ID) REFERENCES IMAGE_TAG(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_image_layer_tag_mapping_updated_at
  AFTER UPDATE ON IMAGE_LAYER_TAG_MAPPING
BEGIN
  UPDATE IMAGE_LAYER_TAG_MAPPING SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

CREATE TABLE IF NOT EXISTS IMAGE_MANIFEST (
  ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))), 
  DIGEST TEXT NOT NULL,
  SIZE INTEGER NOT NULL,
  MEDIA_TYPE TEXT NOT NULL,
  MANIFEST_CONTENT BLOB NOT NULL,
  IMAGE_CONFIG_DIGEST TEXT NOT NULL,
  NAMESPACE_ID TEXT NOT NULL,
  REGISTRY_ID TEXT NOT NULL,
  REPOSITORY_ID TEXT NOT NULL,
  --  Create a semantic digest by combining config and layer digests to identify
  --  logically identical images that may have different manifest digests due to
  --  compression variations or JSON formatting differences.
  --  Format: "config_digest:layer1_digest:layer2_digest:..." -> SHA256
  UNIQUE_DIGEST TEXT NOT NULL, 
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (REGISTRY_ID, NAMESPACE_ID,REPOSITORY_ID, UNIQUE_DIGEST),
  FOREIGN KEY (REPOSITORY_ID) REFERENCES REGISTRY_REPOSITORY(ID) ON DELETE CASCADE,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  FOREIGN KEY (NAMESPACE_ID) REFERENCES REGISTRY_NAMESPACE(ID) ON DELETE CASCADE
);

CREATE TRIGGER IF NOT EXISTS tr_image_manifest_updated_at
  AFTER UPDATE ON IMAGE_MANIFEST
BEGIN
  UPDATE IMAGE_MANIFEST SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;