CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY (
  ID TEXT PRIMARY KEY DEFAULT (HEX(RANDOMBLOB(16))),
  NAME TEXT NOT NULL CHECK(LENGTH(NAME) BETWEEN 3 AND 255),
  URL TEXT NOT NULL CHECK(URL LIKE 'http%' AND LENGTH(URL) <= 2048),
  PORT INTEGER NOT NULL UNIQUE CHECK(PORT BETWEEN 1025 AND 65535),
  STATUS TEXT NOT NULL DEFAULT 'active' CHECK(STATUS IN ('active', 'disabled')),
  UPSTREAM_URL TEXT NOT NULL CHECK(UPSTREAM_URL LIKE 'http%' AND LENGTH(UPSTREAM_URL) <= 2048),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY_AUTH_CONFIG (
  REGISTRY_ID TEXT NOT NULL,
  AUTH_TYPE TEXT NOT NULL DEFAULT 'anonymous' CHECK(AUTH_TYPE IN ('anonymous', 'basic', 'bearer')),
  CREDENTIAL_JSON BLOB CHECK( -- Conditional validation
    (AUTH_TYPE = 'anonymous' AND CREDENTIAL_JSON IS NULL) OR
    (AUTH_TYPE != 'anonymous' AND CREDENTIAL_JSON IS NOT NULL)
  ),
  TOKEN_ENDPOINT TEXT CHECK(TOKEN_ENDPOINT IS NULL OR TOKEN_ENDPOINT LIKE 'http%'),
  CERTIFICATE BLOB,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  UNIQUE(REGISTRY_ID)
);

CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG(
  REGISTRY_ID TEXT NOT NULL,
  PROXY_ENABLED INTEGER NOT NULL DEFAULT 0 CHECK(PROXY_ENABLED IN (0, 1)),
  PROXY_URL TEXT CHECK(PROXY_URL IS NULL OR PROXY_URL LIKE 'http%'),
  CONNECTION_TIMEOUT INTEGER NOT NULL DEFAULT 10 CHECK(CONNECTION_TIMEOUT BETWEEN 1 AND 300),
  READ_TIMEOUT INTEGER NOT NULL DEFAULT 30 CHECK(READ_TIMEOUT BETWEEN 1 AND 600),
  MAX_CONNECTIONS INTEGER NOT NULL DEFAULT 100 CHECK(MAX_CONNECTIONS BETWEEN 1 AND 1000),
  MAX_RETRIES INTEGER NOT NULL DEFAULT 3 CHECK(MAX_RETRIES BETWEEN 0 AND 10),
  RETRY_DELAY INTEGER NOT NULL DEFAULT 5 CHECK(RETRY_DELAY BETWEEN 1 AND 60), 
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  UNIQUE(REGISTRY_ID),
  CHECK (
    (PROXY_ENABLED = 0) OR 
    (PROXY_ENABLED = 1 AND PROXY_URL IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG(
  REGISTRY_ID TEXT NOT NULL,
  STORAGE_LIMIT REAL DEFAULT 10737418240 CHECK(STORAGE_LIMIT >= 104857600), -- 10GB default, min 100MB
  CLEANUP_POLICY TEXT NOT NULL DEFAULT 'LRU_1M' CHECK(CLEANUP_POLICY IN ('LRU_1M', 'LRU_3M', 'LP')), -- LP = LEAST PULLED
  CLEANUP_THRESHOLD_PERCENTAGE REAL NOT NULL DEFAULT 80.0 CHECK(
    CLEANUP_THRESHOLD_PERCENTAGE BETWEEN 10.0 AND 95.0
  ),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  UNIQUE(REGISTRY_ID)
);

CREATE TABLE IF NOT EXISTS UPSTREAM_OCI_REGISTRY_CACHE_CONFIG(
  REGISTRY_ID TEXT NOT NULL,
  TTL_SECONDS INTEGER NOT NULL DEFAULT 2592000 CHECK(TTL_SECONDS BETWEEN 600 AND 31536000), -- 10 mins to 1 year
  OFFLINE_MODE INTEGER NOT NULL DEFAULT 1 CHECK(OFFLINE_MODE IN (0, 1)), -- Changed from BOOLEAN to INTEGER
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (REGISTRY_ID) REFERENCES UPSTREAM_OCI_REGISTRY(ID) ON DELETE CASCADE,
  UNIQUE(REGISTRY_ID)
);


-- Triggers to automatically update UPDATED_AT timestamp
CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY SET UPDATED_AT = CURRENT_TIMESTAMP WHERE ID = NEW.ID;
END;

CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_auth_config_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY_AUTH_CONFIG
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY_AUTH_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE REGISTRY_ID = NEW.REGISTRY_ID;
END;

CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_access_config_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE REGISTRY_ID = NEW.REGISTRY_ID;
END;

CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_storage_config_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE REGISTRY_ID = NEW.REGISTRY_ID;
END;

CREATE TRIGGER IF NOT EXISTS tr_upstream_oci_registry_cache_config_updated_at
  AFTER UPDATE ON UPSTREAM_OCI_REGISTRY_CACHE_CONFIG
BEGIN
  UPDATE UPSTREAM_OCI_REGISTRY_CACHE_CONFIG SET UPDATED_AT = CURRENT_TIMESTAMP WHERE REGISTRY_ID = NEW.REGISTRY_ID;
END;