// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api/v1` | (string & {});
};

export type PaginatedBase = {
    /**
     * Total number of items
     */
    total: number;
    /**
     * Current page number
     */
    page: number;
    /**
     * Items per page
     */
    limit: number;
};

export type ErrorResponse = {
    /**
     * HTTP status code
     */
    error_code: number;
    /**
     * Error message
     */
    error_message: string;
};

export type CreateUserAccountRequest = {
    /**
     * Unique username (3-32 chars, alphanumeric with ._- allowed)
     */
    username: string;
    /**
     * User email address
     */
    email: string;
    /**
     * Display name for the user
     */
    display_name?: string;
    /**
     * User role in the system
     */
    role: 'Admin' | 'Maintainer' | 'Developer' | 'Guest';
};

export type CreateUserAccountResponse = {
    /**
     * Created username
     */
    username: string;
    /**
     * Generated user ID (UUID)
     */
    user_id: string;
};

export type UpdateUserAccountRequest = {
    /**
     * New display name (1-255 chars)
     */
    display_name: string;
};

export type UpdateUserEmailRequest = {
    /**
     * New email address
     */
    email: string;
};

export type ChangeUserRoleRequest = {
    /**
     * New role for the user
     */
    role: 'admin' | 'maintainer' | 'developer' | 'guest';
};

export type PasswordChangeRequest = {
    /**
     * User ID (must match path parameter)
     */
    user_id: string;
    /**
     * Password recovery ID (for admin-initiated resets)
     */
    recovery_id?: string;
    /**
     * New password (12-64 chars, must contain uppercase, lowercase, digit, and symbol !@#$%^&*)
     *
     */
    password: string;
    /**
     * Current password (required for user-initiated changes)
     */
    old_password?: string;
};

export type ChangePasswordResponse = {
    /**
     * Status of password change operation
     */
    status: 'success' | 'failed';
    /**
     * Detailed message about the result
     */
    message: string;
};

export type UsernameEmailValidationRequest = {
    /**
     * Username to validate (optional if email provided)
     */
    username?: string;
    /**
     * Email to validate (optional if username provided)
     */
    email?: string;
};

export type UsernameEmailValidationResponse = {
    /**
     * Whether the username is available
     */
    username_available: boolean;
    /**
     * Whether the email is available
     */
    email_available: boolean;
};

export type GetUserResponse = {
    /**
     * User ID
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Display name
     */
    display_name?: string;
    /**
     * Whether the account is locked
     */
    locked?: boolean;
    /**
     * Numeric code for lock reason
     */
    locked_reason?: number;
    /**
     * Number of failed login attempts
     */
    failed_attempts?: number;
    /**
     * User role
     */
    role: string;
    /**
     * Account creation timestamp
     */
    created_at: string;
    /**
     * Last update timestamp
     */
    updated_at?: string | null;
    /**
     * When account was locked
     */
    locked_at?: string | null;
};

export type UserAccountViewDto = {
    /**
     * User ID
     */
    id: string;
    /**
     * Username
     */
    username: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Display name
     */
    display_name?: string;
    /**
     * Whether account is locked
     */
    locked: boolean;
    /**
     * Human-readable lock reason
     */
    locked_reason?: string;
    /**
     * Lock timestamp
     */
    locked_at?: string | null;
    /**
     * Number of failed login attempts
     */
    failed_attempts: number;
    /**
     * Active password recovery ID
     */
    password_recovery_id?: string;
    /**
     * Human-readable password recovery reason
     */
    password_recovery_reason?: string;
    /**
     * Password recovery creation time
     */
    password_recovery_at?: string | null;
    /**
     * Last successful login
     */
    last_loggedin_at?: string | null;
    /**
     * Account creation time
     */
    created_at: string;
    /**
     * Last update time
     */
    updated_at?: string | null;
    /**
     * User role
     */
    role: string;
};

export type UserAccountSetupInfoResponse = {
    /**
     * Error message if setup info cannot be retrieved (empty on success)
     */
    error_message: string;
    /**
     * Username for the account
     */
    username: string;
    /**
     * User ID
     */
    user_id: string;
    /**
     * Display name
     */
    display_name: string;
    /**
     * Email address
     */
    email: string;
    /**
     * Assigned role
     */
    role: string;
};

export type AccountSetupCompleteRequest = {
    /**
     * User ID from setup info
     */
    user_id: string;
    /**
     * Username from setup info (3-32 chars)
     */
    username: string;
    /**
     * Optional display name
     */
    display_name?: string;
    /**
     * New password (12-64 chars, must contain uppercase, lowercase, digit, and symbol !@#$%^&*)
     *
     */
    password: string;
    /**
     * Setup UUID (must match path parameter)
     */
    uuid: string;
};

export type ResourceAccessViewDto = {
    /**
     * Access record ID
     */
    id: string;
    /**
     * Resource type
     */
    resource_type: 'namespace' | 'repository' | 'upstream';
    /**
     * Human readable resource name
     */
    resource_name: string;
    /**
     * Resource ID
     */
    resource_id: string;
    /**
     * Granted access level
     */
    access_level: 'Guest' | 'Developer' | 'Maintainer';
    /**
     * User ID who owns this access
     */
    user_id: string;
    /**
     * Username of the access owner
     */
    username: string;
    /**
     * Username of the grantor
     */
    granted_user: string;
    /**
     * User ID of the grantor
     */
    granted_by: string;
    /**
     * Access granted timestamp
     */
    granted_at: string;
};

export type NamespaceViewDto = {
    /**
     * Registry ID
     */
    registry_id: string;
    /**
     * Namespace ID
     */
    id: string;
    /**
     * Namespace name
     */
    name: string;
    /**
     * Namespace description
     */
    description?: string;
    /**
     * Current state of namespace
     */
    state: string;
    /**
     * Whether namespace is public
     */
    is_public: boolean;
    purpose: 'Team' | 'Project';
    /**
     * Creation timestamp
     */
    created_at: string;
    /**
     * Last update timestamp
     */
    updated_at?: string | null;
    /**
     * List of developer user IDs
     */
    developers?: Array<string>;
    /**
     * List of maintainer user IDs
     */
    maintainers?: Array<string>;
};

export type CreateNamespaceRequest = {
    name: string;
    description?: string;
    purpose: 'Team' | 'Project';
    is_public?: boolean;
    maintainers: Array<string>;
};

export type CreateNamespaceResponse = {
    id: string;
};

export type UpdateNamespaceRequest = {
    description: string;
    purpose: 'Team' | 'Project';
};

export type NamespaceResponse = {
    id: string;
    registry_id: string;
    name: string;
    description?: string;
    purpose?: 'Team' | 'Project';
    is_public: boolean;
    state: 'Active' | 'Deprecated' | 'Disabled';
    created_at: string;
    updated_at?: string | null;
};

export type AccessGrantRequest = {
    user_id: string;
    resource_id: string;
    resource_type: 'Namespace' | 'Repository' | 'Upstream';
    access_level: 'Guest' | 'Developer' | 'Maintainer';
    granted_by: string;
};

export type UserProfileInfo = {
    user_id: string;
    username: string;
    role: string;
};

/**
 * Page number for pagination
 */
export type PageQuery = number;

/**
 * Number of items per page
 */
export type LimitQuery = number;

/**
 * The direction in which to sort the results.
 */
export type SortOrder = 'asc' | 'desc';

export type SearchQuery = string;

export type PostAuthLoginData = {
    body: {
        username: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * OK. Returns `auth_token` cookie.
     */
    200: UserProfileInfo;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Session revoked.
     */
    200: unknown;
};

export type GetOnboardingByUuidData = {
    body?: never;
    path: {
        /**
         * The account setup UUID provided during user creation
         */
        uuid: string;
    };
    query?: never;
    url: '/onboarding/{uuid}';
};

export type GetOnboardingByUuidErrors = {
    /**
     * Setup UUID not found, already used, or has incorrect recovery reason
     */
    404: UserAccountSetupInfoResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type GetOnboardingByUuidError = GetOnboardingByUuidErrors[keyof GetOnboardingByUuidErrors];

export type GetOnboardingByUuidResponses = {
    /**
     * Account setup information retrieved successfully
     */
    200: UserAccountSetupInfoResponse;
};

export type GetOnboardingByUuidResponse = GetOnboardingByUuidResponses[keyof GetOnboardingByUuidResponses];

export type PostOnboardingByUuidCompleteData = {
    body: AccountSetupCompleteRequest;
    path: {
        /**
         * The account setup UUID
         */
        uuid: string;
    };
    query?: never;
    url: '/onboarding/{uuid}/complete';
};

export type PostOnboardingByUuidCompleteErrors = {
    /**
     * Invalid request or validation error
     */
    400: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PostOnboardingByUuidCompleteError = PostOnboardingByUuidCompleteErrors[keyof PostOnboardingByUuidCompleteErrors];

export type PostOnboardingByUuidCompleteResponses = {
    /**
     * Account activated successfully
     */
    200: unknown;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * The direction in which to sort the results.
         */
        order?: 'asc' | 'desc';
        search?: string;
        /**
         * Sort field.
         */
        sort_by?: 'username' | 'email' | 'role' | 'display_name' | 'last_loggedin_at';
        /**
         * Filter field role; Possible values are 'Admin', 'Developer', 'Maintainer', 'Guest'
         */
        role?: Array<'Admin' | 'Developer' | 'Maintainer' | 'Guest'>;
        /**
         * Filter user accounts by account state
         */
        locked?: boolean;
    };
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * List of users retrieved successfully
     */
    200: PaginatedBase & {
        entities?: Array<UserAccountViewDto>;
    };
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type PostUsersData = {
    body: CreateUserAccountRequest;
    path?: never;
    query?: never;
    url: '/users';
};

export type PostUsersErrors = {
    /**
     * Validation error
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * User already exists (username or email conflict)
     */
    409: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PostUsersError = PostUsersErrors[keyof PostUsersErrors];

export type PostUsersResponses = {
    /**
     * User account created successfully
     */
    201: CreateUserAccountResponse;
};

export type PostUsersResponse = PostUsersResponses[keyof PostUsersResponses];

export type GetUsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type GetUsersMeErrors = {
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type GetUsersMeError = GetUsersMeErrors[keyof GetUsersMeErrors];

export type GetUsersMeResponses = {
    /**
     * Current user information
     */
    200: GetUserResponse;
};

export type GetUsersMeResponse = GetUsersMeResponses[keyof GetUsersMeResponses];

export type PutUsersMeData = {
    body: UpdateUserAccountRequest;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type PutUsersMeErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PutUsersMeError = PutUsersMeErrors[keyof PutUsersMeErrors];

export type PutUsersMeResponses = {
    /**
     * User updated successfully
     */
    200: unknown;
};

export type PostUsersValidateData = {
    body: UsernameEmailValidationRequest;
    path?: never;
    query?: never;
    url: '/users/validate';
};

export type PostUsersValidateErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PostUsersValidateError = PostUsersValidateErrors[keyof PostUsersValidateErrors];

export type PostUsersValidateResponses = {
    /**
     * Validation results
     */
    200: UsernameEmailValidationResponse;
};

export type PostUsersValidateResponse = PostUsersValidateResponses[keyof PostUsersValidateResponses];

export type DeleteUsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type DeleteUsersByIdErrors = {
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type DeleteUsersByIdError = DeleteUsersByIdErrors[keyof DeleteUsersByIdErrors];

export type DeleteUsersByIdResponses = {
    /**
     * User deleted successfully
     */
    200: unknown;
};

export type GetUsersByIdData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type GetUsersByIdErrors = {
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Resource not found.
     */
    404: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type GetUsersByIdError = GetUsersByIdErrors[keyof GetUsersByIdErrors];

export type GetUsersByIdResponses = {
    /**
     * User information retrieved successfully
     */
    200: GetUserResponse;
};

export type GetUsersByIdResponse = GetUsersByIdResponses[keyof GetUsersByIdResponses];

export type PutUsersByIdData = {
    body: UpdateUserAccountRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type PutUsersByIdErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PutUsersByIdError = PutUsersByIdErrors[keyof PutUsersByIdErrors];

export type PutUsersByIdResponses = {
    /**
     * User updated successfully
     */
    200: unknown;
};

export type PutUsersByIdEmailData = {
    body: UpdateUserEmailRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/email';
};

export type PutUsersByIdEmailErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PutUsersByIdEmailError = PutUsersByIdEmailErrors[keyof PutUsersByIdEmailErrors];

export type PutUsersByIdEmailResponses = {
    /**
     * Email updated successfully
     */
    200: unknown;
};

export type PutUsersByIdRoleData = {
    body: ChangeUserRoleRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/role';
};

export type PutUsersByIdRoleErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Operation not allowed
     */
    403: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PutUsersByIdRoleError = PutUsersByIdRoleErrors[keyof PutUsersByIdRoleErrors];

export type PutUsersByIdRoleResponses = {
    /**
     * Role changed successfully
     */
    200: unknown;
};

export type PutUsersByIdPasswordData = {
    body: PasswordChangeRequest;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/password';
};

export type PutUsersByIdPasswordErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PutUsersByIdPasswordError = PutUsersByIdPasswordErrors[keyof PutUsersByIdPasswordErrors];

export type PutUsersByIdPasswordResponses = {
    /**
     * Password change result
     */
    200: ChangePasswordResponse;
};

export type PutUsersByIdPasswordResponse = PutUsersByIdPasswordResponses[keyof PutUsersByIdPasswordResponses];

export type PutUsersByIdLockData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/lock';
};

export type PutUsersByIdLockErrors = {
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * User account is already locked
     */
    409: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PutUsersByIdLockError = PutUsersByIdLockErrors[keyof PutUsersByIdLockErrors];

export type PutUsersByIdLockResponses = {
    /**
     * User account locked successfully
     */
    200: unknown;
};

export type PutUsersByIdUnlockData = {
    body?: never;
    path: {
        /**
         * User ID
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}/unlock';
};

export type PutUsersByIdUnlockErrors = {
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Cannot unlock new user account
     */
    409: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PutUsersByIdUnlockError = PutUsersByIdUnlockErrors[keyof PutUsersByIdUnlockErrors];

export type PutUsersByIdUnlockResponses = {
    /**
     * User account unlocked successfully
     */
    200: unknown;
};

export type GetResourceNamespacesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        order?: 'asc' | 'desc';
        search?: string;
        /**
         * Sort field
         */
        sort_by?: 'name' | 'created_at';
        state?: 'Active' | 'Deprecated' | 'Disabled';
        purpose?: 'Team' | 'Project';
        is_public?: boolean;
    };
    url: '/resource/namespaces';
};

export type GetResourceNamespacesErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type GetResourceNamespacesError = GetResourceNamespacesErrors[keyof GetResourceNamespacesErrors];

export type GetResourceNamespacesResponses = {
    /**
     * List of namespaces retrieved successfully
     */
    200: PaginatedBase & {
        entities?: Array<NamespaceViewDto>;
    };
};

export type GetResourceNamespacesResponse = GetResourceNamespacesResponses[keyof GetResourceNamespacesResponses];

export type PostResourceNamespacesData = {
    body: CreateNamespaceRequest;
    path?: never;
    query?: never;
    url: '/resource/namespaces';
};

export type PostResourceNamespacesErrors = {
    /**
     * Malformed request or validation error.
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Access forbidden.
     */
    403: ErrorResponse;
    /**
     * Resource not found.
     */
    404: ErrorResponse;
    /**
     * Conflict with existing resource.
     */
    409: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PostResourceNamespacesError = PostResourceNamespacesErrors[keyof PostResourceNamespacesErrors];

export type PostResourceNamespacesResponses = {
    /**
     * Namespace created successfully
     */
    201: CreateNamespaceResponse;
};

export type PostResourceNamespacesResponse = PostResourceNamespacesResponses[keyof PostResourceNamespacesResponses];

export type DeleteResourceNamespacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/resource/namespaces/{id}';
};

export type DeleteResourceNamespacesByIdResponses = {
    /**
     * Namespace deleted successfully
     */
    200: unknown;
};

export type GetResourceNamespacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/resource/namespaces/{id}';
};

export type GetResourceNamespacesByIdErrors = {
    /**
     * Resource not found.
     */
    404: ErrorResponse;
};

export type GetResourceNamespacesByIdError = GetResourceNamespacesByIdErrors[keyof GetResourceNamespacesByIdErrors];

export type GetResourceNamespacesByIdResponses = {
    /**
     * OK
     */
    200: NamespaceResponse;
};

export type GetResourceNamespacesByIdResponse = GetResourceNamespacesByIdResponses[keyof GetResourceNamespacesByIdResponses];

export type HeadResourceNamespacesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/resource/namespaces/{id}';
};

export type HeadResourceNamespacesByIdErrors = {
    /**
     * Namespace not found
     */
    404: unknown;
};

export type HeadResourceNamespacesByIdResponses = {
    /**
     * Namespace exists
     */
    200: unknown;
};

export type PutResourceNamespacesByIdData = {
    body: UpdateNamespaceRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/resource/namespaces/{id}';
};

export type PutResourceNamespacesByIdResponses = {
    /**
     * Namespace updated successfully
     */
    200: unknown;
};

export type PatchResourceNamespacesByIdVisibilityData = {
    body?: never;
    path: {
        /**
         * Namespace ID or name
         */
        id: string;
    };
    query: {
        /**
         * Whether namespace should be public
         */
        public: boolean;
    };
    url: '/resource/namespaces/{id}/visibility';
};

export type PatchResourceNamespacesByIdVisibilityErrors = {
    /**
     * Invalid query parameter
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Namespace not found
     */
    404: ErrorResponse;
    /**
     * Visibility change not allowed
     */
    422: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PatchResourceNamespacesByIdVisibilityError = PatchResourceNamespacesByIdVisibilityErrors[keyof PatchResourceNamespacesByIdVisibilityErrors];

export type PatchResourceNamespacesByIdVisibilityResponses = {
    /**
     * Visibility changed successfully or no-op
     */
    200: unknown;
};

export type PatchResourceNamespacesByIdStateData = {
    body?: never;
    path: {
        /**
         * Namespace ID or name
         */
        id: string;
    };
    query: {
        /**
         * New namespace state
         */
        state: 'Active' | 'Deprecated' | 'Disabled';
    };
    url: '/resource/namespaces/{id}/state';
};

export type PatchResourceNamespacesByIdStateErrors = {
    /**
     * Invalid or missing state query parameter
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Namespace not found
     */
    404: ErrorResponse;
    /**
     * State transition not allowed
     */
    422: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PatchResourceNamespacesByIdStateError = PatchResourceNamespacesByIdStateErrors[keyof PatchResourceNamespacesByIdStateErrors];

export type PatchResourceNamespacesByIdStateResponses = {
    /**
     * State changed successfully or no-op if same state
     */
    200: unknown;
};

export type GetResourceNamespacesByIdUsersData = {
    body?: never;
    path: {
        /**
         * Namespace ID
         */
        id: string;
    };
    query?: {
        /**
         * Page number for pagination
         */
        page?: number;
        /**
         * Number of items per page
         */
        limit?: number;
        /**
         * The direction in which to sort the results.
         */
        order?: 'asc' | 'desc';
        /**
         * Search by username
         */
        search?: string;
        /**
         * Filter by access level
         */
        access_level?: 'Guest' | 'Developer' | 'Maintainer';
        /**
         * The field used to sort the results.
         */
        sort_by?: 'user' | 'granted_user' | 'granted_at';
    };
    url: '/resource/namespaces/{id}/users';
};

export type GetResourceNamespacesByIdUsersErrors = {
    /**
     * Invalid filter or sort field
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Namespace not found
     */
    404: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type GetResourceNamespacesByIdUsersError = GetResourceNamespacesByIdUsersErrors[keyof GetResourceNamespacesByIdUsersErrors];

export type GetResourceNamespacesByIdUsersResponses = {
    /**
     * List of user accesses retrieved successfully
     */
    200: PaginatedBase & {
        entities?: Array<ResourceAccessViewDto>;
    };
};

export type GetResourceNamespacesByIdUsersResponse = GetResourceNamespacesByIdUsersResponses[keyof GetResourceNamespacesByIdUsersResponses];

export type PostResourceNamespacesByIdUsersData = {
    body: AccessGrantRequest;
    path: {
        /**
         * Namespace ID
         */
        id: string;
    };
    query?: never;
    url: '/resource/namespaces/{id}/users';
};

export type PostResourceNamespacesByIdUsersErrors = {
    /**
     * Invalid request body, invalid resource_type, or validation failure
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * Access level not permitted for user role
     */
    403: ErrorResponse;
    /**
     * User or namespace not found, or resource_id mismatch
     */
    404: ErrorResponse;
    /**
     * Access already exists and cannot be overwritten
     */
    409: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type PostResourceNamespacesByIdUsersError = PostResourceNamespacesByIdUsersErrors[keyof PostResourceNamespacesByIdUsersErrors];

export type PostResourceNamespacesByIdUsersResponses = {
    /**
     * Access granted successfully
     */
    200: unknown;
};

export type DeleteResourceNamespacesByIdUsersByUserIdData = {
    body?: never;
    path: {
        /**
         * Namespace ID
         */
        id: string;
        /**
         * User ID
         */
        userID: string;
    };
    query?: never;
    url: '/resource/namespaces/{id}/users/{userID}';
};

export type DeleteResourceNamespacesByIdUsersByUserIdErrors = {
    /**
     * Invalid body or invalid resource_type
     */
    400: ErrorResponse;
    /**
     * Invalid, expired, or revoked session cookie.
     */
    401: ErrorResponse;
    /**
     * User not found, namespace not found, or access does not exist
     */
    404: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type DeleteResourceNamespacesByIdUsersByUserIdError = DeleteResourceNamespacesByIdUsersByUserIdErrors[keyof DeleteResourceNamespacesByIdUsersByUserIdErrors];

export type DeleteResourceNamespacesByIdUsersByUserIdResponses = {
    /**
     * Access revoked successfully
     */
    200: unknown;
};

export type GetResourceNamespacesCheckNameData = {
    body?: never;
    path?: never;
    query: {
        /**
         * The namespace name to validate
         */
        name: string;
    };
    url: '/resource/namespaces/check-name';
};

export type GetResourceNamespacesCheckNameErrors = {
    /**
     * Name does not match the required regex pattern
     */
    400: ErrorResponse;
    /**
     * Internal server error.
     */
    500: ErrorResponse;
};

export type GetResourceNamespacesCheckNameError = GetResourceNamespacesCheckNameErrors[keyof GetResourceNamespacesCheckNameErrors];

export type GetResourceNamespacesCheckNameResponses = {
    /**
     * Check performed successfully
     */
    200: {
        /**
         * True if the name is not taken and is valid.
         */
        available?: boolean;
    };
};

export type GetResourceNamespacesCheckNameResponse = GetResourceNamespacesCheckNameResponses[keyof GetResourceNamespacesCheckNameResponses];
