package sqlite

const (
	NamespaceCreateQuery             = `INSERT INTO REGISTRY_NAMESPACE (REGISTRY_ID, NAME, DESCRIPTION, PURPOSE, IS_PUBLIC) VALUES (?, ?, ?, ?, ?) RETURNING ID`
	NamespaceGetQuery                = `SELECT REGISTRY_ID, NAME, DESCRIPTION, PURPOSE, IS_PUBLIC, STATE, CREATED_AT, UPDATED_AT FROM REGISTRY_NAMESPACE WHERE ID = ?`
	NamespaceGetByNameQuery          = `SELECT REGISTRY_ID, NAME, DESCRIPTION, PURPOSE, IS_PUBLIC, STATE, CREATED_AT, UPDATED_AT FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND NAME = ?`
	NamespaceGetIDQuery              = `SELECT ID FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND NAME = ?`
	NamespaceDeleteQuery             = `DELETE FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND ID = ?`
	NamespaceDeleteByIdentifierQuery = `DELETE FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND (ID = ? OR NAME = ?)`
	NamespaceDeleteAll               = `DELETE FROM REGISTRY_NAMESPACE`
	NamespaceExistsByIdentifierQuery = `SELECT 1 FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND (ID = ? OR NAME = ?)`
	NamespaceGetByIdentifierQuery    = `SELECT ID, REGISTRY_ID, NAME, DESCRIPTION, PURPOSE, IS_PUBLIC, STATE, CREATED_AT, UPDATED_AT FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND (ID = ? OR NAME = ?)`
	NamespaceSetStateQuery           = `UPDATE REGISTRY_NAMESPACE SET STATE = ? WHERE ID = ?`
	NamespaceUpdateQuery             = `UPDATE REGISTRY_NAMESPACE SET DESCRIPTION = ?, PURPOSE = ? WHERE ID = ?`
	NamespaceSetVisiblityQuery       = `UPDATE REGISTRY_NAMESPACE SET IS_PUBLIC = ? WHERE ID = ?`
	// IMPORTANT: Base list query avoids WHERE keywords because if we have it in one of the subquery, it will confuse query
	// builder. Current query builder checks WHERE keyword exists or not (not intelligent enough to understand sub queries)
	// then append WHERE at the end of base if needed
	NamespaceListBaseQuery = `
	SELECT 
		rn.REGISTRY_ID AS REGISTRY_ID,
		rn.ID AS ID,
		rn.NAME AS NAME,
		rn.DESCRIPTION AS DESCRIPTION,
		rn.PURPOSE AS PURPOSE,
		rn.IS_PUBLIC AS IS_PUBLIC,
		rn.STATE AS STATE,
		rn.CREATED_AT AS CREATED_AT,
		rn.UPDATED_AT AS UPDATED_AT,
		au.MAINTAINERS AS MAINTAINERS,
		au.DEVELOPERS AS DEVELOPERS
	FROM REGISTRY_NAMESPACE rn
	LEFT JOIN (
		SELECT 
			ra.RESOURCE_ID,
			GROUP_CONCAT(CASE WHEN ra.ACCESS_LEVEL = 'maintainer' THEN ua.USERNAME END) AS MAINTAINERS,
			GROUP_CONCAT(CASE WHEN ra.ACCESS_LEVEL = 'developer' THEN ua.USERNAME END) AS DEVELOPERS
		FROM RESOURCE_ACCESS ra
		JOIN USER_ACCOUNT ua ON ra.USER_ID = ua.ID 
			AND ra.RESOURCE_TYPE = 'namespace' 
			AND ra.ACCESS_LEVEL IN ('maintainer', 'developer')
		GROUP BY ra.RESOURCE_ID
	) AS au ON au.RESOURCE_ID = rn.ID`
	NamespaceCountBaseQuery = `SELECT count(*) FROM REGISTRY_NAMESPACE rn `
)

const (
	RepositoryCreateQuery                  = `INSERT INTO REGISTRY_REPOSITORY(NAME, DESCRIPTION, IS_PUBLIC, NAMESPACE_ID, REGISTRY_ID, CREATED_BY) VALUES(?, ?, ?, ?, ?, ?) RETURNING ID`
	RepositoryGetQuery                     = `SELECT ID, NAME, DESCRIPTION, IS_PUBLIC, STATE, NAMESPACE_ID, REGISTRY_ID, CREATED_AT, UPDATED_AT, CREATED_BY FROM REGISTRY_REPOSITORY WHERE ID = ?`
	RepositoryDeleteQuery                  = `DELETE FROM REGISTRY_REPOSITORY WHERE ID = ?`
	RepositoryUpdateQuery                  = `UPDATE REGISTRY_REPOSITORY SET DESCRIPTION = ? WHERE ID = ?`
	RepositoryGetIDQuery                   = `SELECT ID FROM REGISTRY_REPOSITORY WHERE NAMESPACE_ID = ? AND NAME = ?`
	RepositoryExistsQuery                  = `SELECT 1 FROM REGISTRY_REPOSITORY WHERE ID = ?`
	RepositoryGetByIdentifierQuery         = `SELECT ID, NAME, DESCRIPTION, IS_PUBLIC, STATE, NAMESPACE_ID, REGISTRY_ID, CREATED_AT, UPDATED_AT, CREATED_BY  WHERE NAMESPACE_ID = ? AND (ID = ? OR NAME = ?)`
	RepositoryExistsByIdentifierQuery      = `SELECT 1 FROM REGISTRY_REPOSITORY WHERE NAMESPACE_ID = ? AND (ID = ? OR NAME = ?)`
	RepositoryDeleteByIdentifierQuery      = `DELETE FROM REGISTRY_REPOSITORY WHERE NAMESPACE_ID = ? AND (ID = ? OR NAME = ?)`
	RepositorySetStateQuery                = `UPDATE REGISTRY_REPOSITORY SET STATE = ? WHERE ID = ?`
	RepositorySetVisiblityQuery            = `UPDATE REGISTRY_REPOSITORY SET IS_PUBLIC = ? WHERE ID = ?`
	RepositorySetStateByNamespaceQuery     = `UPDATE REGISTRY_REPOSITORY SET STATE = ? WHERE NAMESPACE_ID = ?`
	RepositorySetVisiblityByNamespaceQuery = `UPDATE REGISTRY_REPOSITORY SET IS_PUBLIC = ? WHERE NAMESPACE_ID = ?`
	// IMPORTANT: Base list query avoids WHERE keywords because if we have it in one of the subquery, it will confuse query
	// builder. Current query builder checks WHERE keyword exists or not (not intelligent enough to understand sub queries)
	// then append WHERE at the end of base if needed
	RepositoryListBaseQuery = `
	SELECT * FROM (
		SELECT 
			rr.REGISTRY_ID AS REGISTRY_ID,
			rr.ID AS ID,
			rr.NAME AS NAME,
			rr.DESCRIPTION AS DESCRIPTION,
			rn.NAME AS NAMESPACE,
			rr.IS_PUBLIC AS IS_PUBLIC,
			rr.STATE AS STATE,
			rr.NAMESPACE_ID AS NAMESPACE_ID,
			rr.CREATED_AT AS CREATED_AT,
			rr.UPDATED_AT AS UPDATED_AT,
			ua.USERNAME AS CREATED_BY,
			COUNT(it.ID) AS TAGS
		FROM REGISTRY_REPOSITORY rr
		LEFT JOIN IMAGE_TAG it ON it.REPOSITORY_ID = rr.ID
		LEFT JOIN REGISTRY_NAMESPACE rn ON rn.ID = rr.NAMESPACE_ID
		LEFT JOIN USER_ACCOUNT ua ON ua.ID = rr.CREATED_BY
		GROUP BY rr.ID
	) AS repositories`
	RepositoryCountBaseQuery = `SELECT COUNT(*) FROM REGISTRY_REPOSITORY`
)

const (
	TagCreateQuery         = `INSERT INTO IMAGE_TAG(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, IS_STABLE, TAG) VALUES(?, ?, ?, ?, ?) RETURNING ID`
	TagGetQuery            = `SELECT REGISTRY_ID, NAMESPACE_ID, ID, TAG, IS_STABLE, CREATED_AT, UPDATED_AT FROM IMAGE_TAG WHERE REPOSITORY_ID = ? AND TAG = ?`
	TagDeleteQuery         = `DELETE FROM IMAGE_TAG WHERE REPOSITORY_ID = ? AND TAG = ?`
	TagLinkManifestQuery   = `INSERT INTO IMAGE_MANIFEST_TAG_MAPPING(MANIFEST_ID, TAG_ID) VALUES(?, ?)`
	TagUpdateManifestQuery = `UPDATE IMAGE_MANIFEST_TAG_MAPPING SET MANIFEST_ID = ? WHERE TAG_ID = ?`
	TagUnlinkManifestQuery = `DELETE FROM IMAGE_MANIFEST_TAG_MAPPING WHERE TAG_ID = ?`
	TagGetManifestID       = `SELECT MANIFEST_ID FROM IMAGE_MANIFEST_TAG_MAPPING WHERE TAG_ID = ?`
)

const (
	AccountRecoveryCreateQuery         = `INSERT INTO USER_ACCOUNT_RECOVERY(RECOVERY_UUID, USER_ID, REASON_TYPE) VALUES(?, ?, ?)`
	AccountRecoveryGetQuery            = `SELECT RECOVERY_UUID, USER_ID, REASON_TYPE, CREATED_AT FROM USER_ACCOUNT_RECOVERY WHERE RECOVERY_UUID = ?`
	AccountRecoveryGetByUserIDQuery    = `SELECT RECOVERY_UUID, USER_ID, REASON_TYPE, CREATED_AT FROM USER_ACCOUNT_RECOVERY WHERE USER_ID = ?`
	AccountRecoveeryDeleteQuery        = `DELETE FROM USER_ACCOUNT_RECOVERY WHERE RECOVERY_UUID = ?`
	AccountRecoveryDeleteByUserIDQuery = `DELETE FROM USER_ACCOUNT_RECOVERY WHERE USER_ID = ?`
	AccountRecoveryUpdateReasonQuery   = `UPDATE USER_ACCOUNT_RECOVERY SET REASON_TYPE = ? WHERE RECOVERY_UUID =?`
)

const (
	ManifestCreateQuery                       = `INSERT INTO IMAGE_MANIFEST(DIGEST, SIZE, MEDIA_TYPE, MANIFEST_CONTENT, NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, UNIQUE_DIGEST) VALUES(?, ?, ?, ?, ?, ?, ?, ?)`
	ManifestGetbyUniqueDigestWithContentQuery = `SELECT ID, DIGEST, SIZE, MEDIA_TYPE, MANIFEST_CONTENT, NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, UNIQUE_DIGEST, CREATED_AT, UPDATED_AT FROM IMAGE_MANIFEST WHERE UNIQUE_DIGEST = ?`
	ManifestGetbyUniqueDigestQuery            = `SELECT ID, DIGEST, SIZE, MEDIA_TYPE, NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, UNIQUE_DIGEST, CREATED_AT, UPDATED_AT FROM IMAGE_MANIFEST WHERE UNIQUE_DIGEST = ?`
	ManifestGetbyDigestWithContentQuery       = `SELECT ID, DIGEST, SIZE, MEDIA_TYPE, MANIFEST_CONTENT, NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, UNIQUE_DIGEST, CREATED_AT, UPDATED_AT FROM IMAGE_MANIFEST WHERE DIGEST = ?`
	ManifestGetbyDigestQuery                  = `SELECT ID, DIGEST, SIZE, MEDIA_TYPE, NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, UNIQUE_DIGEST, CREATED_AT, UPDATED_AT FROM IMAGE_MANIFEST WHERE UNIQUE_DIGEST = ?`
	ManifestDeleteByDigest                    = `DELETE FROM IMAGE_MANIFEST WHERE REPOSITORY_ID = ? AND DIGEST = ?`
)

const (
	BlobMetaCreateQuery = `INSERT INTO IMAGE_BLOB_META(NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, BLOB_DIGEST, SIZE, LOCATION) VALUES(?, ?, ?, ?, ?, ?)`
	BlobMetaGetQuery    = `SELECT NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, BLOB_DIGEST, SIZE, LOCATION, CREATED_AT, UPDATED_AT FROM IMAGE_BLOB_META WHERE REPOSITORY_ID = ? AND BLOB_DIGEST = ?`

	BlobSessionCreateQuery = `INSERT INTO IMAGE_BLOB_UPLOAD_SESSION(SESSION_ID, NAMESPACE_ID, REPOSITORY_ID) VALUES(?, ?, ?)`
	BlobSessionUpdateQuery = `UPDATE IMAGE_BLOB_UPLOAD_SESSION SET BYTES_RECEIVED = ? WHERE SESSION_ID = ?`
	BlobSessionDeleteQuery = `DELETE FROM IMAGE_BLOB_UPLOAD_SESSION WHERE SESSION_ID = ?`
	BlobSessionGetQuery    = `SELECT SESSION_ID, NAMESPACE_ID, REPOSITORY_ID, BYTES_RECEIVED, CREATED_AT, UPDATED_AT FROM IMAGE_BLOB_UPLOAD_SESSION WHERE SESSION_ID = ?`
)

const (
	CacheCreateEntryQuery  = `INSERT INTO IMAGE_REGISTRY_CACHE(NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, IDENTIFIER, DIGEST, EXPIRES_AT) VALUES (?, ?, ?, ?, ?, ?)`
	CacheGetEntryQuery     = `SELECT NAMESPACE_ID, REGISTRY_ID, REPOSITORY_ID, IDENTIFIER, DIGEST, EXPIRES_AT, CREATED_AT, UPDATED_AT FROM IMAGE_REGISTRY_CACHE WHERE REPOSITORY_ID = ? AND IDENTIFIER = ?`
	CacheDeleteEntryQuery  = `DELETE FROM IMAGE_REGISTRY_CACHE WHERE REPOSITORY_ID = ? AND IDENTIFIER = ?`
	CacheRefreshEntryQuery = `UPDATE IMAGE_REGISTRY_CACHE SET EXPIRES_AT = ? WHERE REPOSITORY_ID = ? AND IDENTIFIER = ?`
)

const (
	UserCreateAccountQuery               = `INSERT INTO USER_ACCOUNT(USERNAME, EMAIL, DISPLAY_NAME, PASSWORD, SALT) VALUES(?, ?, ?, ?, ?) RETURNING ID`
	UserDeleteAccountQuery               = `UPDATE USER_ACCOUNT SET DELETED = 1, USERNAME = '[DELETED]' || USERNAME, EMAIL = '[DELETED]' || EMAIL, PASSWORD = '[DELETED]', SALT = '[DELETED]' WHERE ID = ?`
	UserUpdateAccountQuery               = `UPDATE USER_ACCOUNT SET DISPLAY_NAME = ? WHERE ID = ?`
	UserUpdateEmailAccountQuery          = `UPDATE USER_ACCOUNT SET EMAIL = ? WHERE ID = ?`
	UserUpdateDisplayNameAccountQuery    = `UPDATE USER_ACCOUNT SET DISPLAY_NAME = ? WHERE ID = ?`
	UserLockUserAccountByUsernameQuery   = `UPDATE USER_ACCOUNT SET LOCKED = 1, LOCKED_REASON  = ?, LOCKED_AT = CURRENT_TIMESTAMP   WHERE USERNAME = ?`
	UserUnlockUserAccountByUsernameQuery = `UPDATE USER_ACCOUNT SET LOCKED = 0, LOCKED_REASON = 0, LOCKED_AT = NULL WHERE USERNAME = ?`
	UserLockUserAccountQuery             = `UPDATE USER_ACCOUNT SET LOCKED = 1, LOCKED_REASON  = ?, LOCKED_AT = CURRENT_TIMESTAMP   WHERE ID = ?`
	UserUnlockUserAccountQuery           = `UPDATE USER_ACCOUNT SET LOCKED = 0, LOCKED_REASON = 0, LOCKED_AT = NULL WHERE ID = ?`
	UserIncrementFailedAttemptQuery      = `UPDATE USER_ACCOUNT SET FAILED_ATTEMPTS = FAILED_ATTEMPTS + 1  WHERE USERNAME = ?`
	UserUpdatePasswordQuery              = `UPDATE USER_ACCOUNT SET PASSWORD = ?, SALT = ? WHERE ID = ?`
	UserValidateUsernameAndEmailQuery    = `SELECT acc.USERNAME, acc.EMAIL FROM USER_ACCOUNT acc WHERE USERNAME = ? OR EMAIL = ?`
	UserGetPasswordAndSaltQuery          = `SELECT PASSWORD, SALT FROM USER_ACCOUNT WHERE DELETED = 0 AND ID = ?`
	UserGetUserAccountByUsernameQuery    = `SELECT ID, USERNAME, EMAIL, DISPLAY_NAME, LOCKED, LOCKED_REASON, FAILED_ATTEMPTS, CREATED_AT, UPDATED_AT, LOCKED_AT
		FROM USER_ACCOUNT
		WHERE DELETED = 0 AND USERNAME = ?
	`
	UserGetUserAccountQuery = `SELECT ID, USERNAME, EMAIL, DISPLAY_NAME, LOCKED, LOCKED_REASON, FAILED_ATTEMPTS, CREATED_AT, UPDATED_AT, LOCKED_AT
		FROM USER_ACCOUNT
		WHERE DELETED = 0 AND (ID = ? OR USERNAME = ?)
	`
	// IMPORTANT: Base list query avoids WHERE keywords because if we have it in one of the subquery, it will confuse query
	// builder. Current query builder checks WHERE keyword exists or not (not intelligent enough to understand sub queries)
	// then append WHERE at the end of base if needed
	UserListBaseQuery = `SELECT acc.ID,
       acc.USERNAME,
       acc.EMAIL,
       acc.DISPLAY_NAME,
       acc.LOCKED,
       acc.LOCKED_REASON,
       acc.LOCKED_AT,
       acc.FAILED_ATTEMPTS,
       acc.CREATED_AT,
       acc.UPDATED_AT,
       ra.ROLE_NAME,
       ar.RECOVERY_UUID,
       ar.REASON_TYPE,
       ar.CREATED_AT AS PW_RECOVERY_AT,
			 acc.LAST_ACCESSED_AT as LAST_LOGGEDIN_AT
	FROM USER_ACCOUNT acc
	LEFT JOIN USER_ACCOUNT_RECOVERY ar ON acc.ID = ar.USER_ID
	LEFT JOIN USER_ROLE_ASSIGNMENT ra ON acc.ID = ra.USER_ID
	LEFT JOIN OAUTH_AUTH_SESSION session ON acc.ID = session.USER_ID
	WHERE acc.DELETED = 0
`
	UserCountActiveAccountByIdsQuery = `SELECT COUNT(*) FROM USER_ACCOUNT WHERE ID IN (%s) AND DELETED = 0 AND LOCKED = 0`

	UserCountBaseQuery = `SELECT COUNT(*)
	FROM USER_ACCOUNT acc
	LEFT JOIN USER_ACCOUNT_RECOVERY ar ON acc.ID = ar.USER_ID
	LEFT JOIN USER_ROLE_ASSIGNMENT ra ON acc.ID = ra.USER_ID
	LEFT JOIN OAUTH_AUTH_SESSION session ON acc.ID = session.USER_ID
	WHERE acc.DELETED = 0`

	UserGetRoleQuery           = `SELECT ROLE_NAME FROM USER_ROLE_ASSIGNMENT WHERE USER_ID = ?`
	UserAssignRoleQuery        = `INSERT INTO USER_ROLE_ASSIGNMENT (USER_ID, ROLE_NAME) VALUES(?, ?)`
	UserUnassignRoleQuery      = `DELETE FROM USER_ROLE_ASSIGNMENT WHERE USER_ID = ?`
	UserRecordLastAccessedTime = `UPDATE USER_ACCOUNT SET LAST_ACCESSED_AT = ? WHERE ID = ?`
)

const (
	ResourceAccessGrantQuery  = `INSERT INTO RESOURCE_ACCESS(RESOURCE_TYPE, RESOURCE_ID, USER_ID, ACCESS_LEVEL, GRANTED_BY) VALUES(?, ?, ?, ?, ?) RETURNING ID`
	ResourceAccessRevokeQuery = `DELETE FROM RESOURCE_ACCESS WHERE RESOURCE_ID = ? AND RESOURCE_TYPE = ? AND USER_ID = ?`
	// IMPORTANT: Base list query avoids WHERE keywords because if we have it in one of the subquery, it will confuse query
	// builder. Current query builder checks WHERE keyword exists or not (not intelligent enough to understand sub queries)
	// then append WHERE at the end of base if needed
	ResourceAccessListBaseQuery = `
	SELECT
		ra.ID AS ID,
		ra.RESOURCE_TYPE AS RESOURCE_TYPE,
		rn.NAME AS NAMESPACE,
		rr.NAME AS REPOSITORY,
		ra.RESOURCE_ID AS RESOURCE_ID,
		ra.USER_ID AS USER_ID,
		ra.ACCESS_LEVEL AS ACCESS_LEVEL,
		ua.USERNAME AS USER,
		ua1.USERNAME AS GRANTED_USER,
		ra.GRANTED_BY AS GRANTED_BY,
		ra.CREATED_AT AS CREATED_AT
	FROM RESOURCE_ACCESS ra
	JOIN USER_ACCOUNT ua ON ra.USER_ID = ua.ID
	JOIN USER_ACCOUNT ua1 ON ra.GRANTED_BY = ua1.ID
	LEFT JOIN REGISTRY_NAMESPACE rn ON ra.RESOURCE_ID = rn.ID AND ra.RESOURCE_TYPE = 'namespace'
	LEFT JOIN REGISTRY_REPOSITORY rr ON ra.RESOURCE_ID = rr.ID AND ra.RESOURCE_TYPE = 'repository'
	WHERE ua.DELETED = 0`
	ResourceAccessCountBaseQuery = `SELECT count(*) FROM RESOURCE_ACCESS ra
	JOIN USER_ACCOUNT ua ON ra.USER_ID = ua.ID
	JOIN USER_ACCOUNT ua1 ON ra.GRANTED_BY = ua1.ID
	LEFT JOIN REGISTRY_NAMESPACE rn ON ra.RESOURCE_ID = rn.ID AND ra.RESOURCE_TYPE = 'namespace'
	LEFT JOIN REGISTRY_REPOSITORY rr ON ra.RESOURCE_ID = rr.ID AND ra.RESOURCE_TYPE = 'repository'
	WHERE ua.DELETED = 0`

	ResourceAccessGetByUserAndResourceQuery = `SELECT ID, ACCESS_LEVEL, GRANTED_BY, CREATED_AT FROM RESOURCE_ACCESS WHERE USER_ID = ? AND RESOURCE_TYPE = ? AND RESOURCE_ID = ?`
)

const (
	CountMaintainersByIdsQuery      = `SELECT COUNT(*) FROM USER_ROLE_ASSIGNMENT WHERE USER_ID IN (%s)`
	CountMatchingUsersByIDs         = `SELECT COUNT(*) FROM USER_ACCOUNT WHERE ID IN (%s) AND DELETED = 0`
	CountMatchingUsersByIDsAndRoles = `SELECT COUNT(*) FROM USER_ACCOUNT ua
	LEFT JOIN USER_ROLE_ASSIGNMENT ura ON ua.ID = ura.USER_ID
	WHERE ura.USER_ID IN (%s) AND ura.ROLE_NAME IN (%s) AND ua.DELETED = 0
	`
	CountMatchingUsersHaveAccessToResource = `SELECT COUNT(DISTINCT USER_ID) FROM RESOURCE_ACCESS WHERE RESOURCE_TYPE = ? AND RESOURCE_ID = ? AND USER_ID IN (%s)`
	ValidateUsersAccessEligibility         = `SELECT COUNT(*) FROM USER_ROLE_ASSIGNMENT WHERE USER_ID IN(%s) AND ROLE_NAME IN (%s)`
)

const (
	RecordTokenRevocationQuery = `INSERT INTO REVOKED_TOKENS(SIGNATURE_HASH, EXPIRES_AT, ISSUED_AT, USER_ID) VALUES(?, ?, ?, ?)`
	GetRevokedTokenQuery       = `SELECT SIGNATURE_HASH, EXPIRES_AT, ISSUED_AT, USER_ID FROM REVOKED_TOKENS WHERE SIGNATURE_HASH = ?`
)

const (
	GetManifestWithContentByTagQuery = `SELECT im.ID, im.DIGEST, im.SIZE, im.MEDIA_TYPE, im.MANIFEST_CONTENT,
	  im.NAMESPACE_ID, im.REGISTRY_ID, im.REPOSITORY_ID, im.UNIQUE_DIGEST, im.CREATED_AT, im.UPDATED_AT
		FROM IMAGE_MANIFEST im 
		JOIN IMAGE_MANIFEST_TAG_MAPPING imtm  on imtm.MANIFEST_ID = im.ID
		JOIN IMAGE_TAG it ON it.ID = imtm.TAG_ID
		WHERE im.REPOSITORY_ID  = ? AND it.TAG = ?`

	GetManifestByTagQuery = `SELECT im.ID, im.DIGEST, im.SIZE, im.MEDIA_TYPE, im.MANIFEST_CONTENT,
	  im.NAMESPACE_ID, im.REGISTRY_ID, im.REPOSITORY_ID, im.UNIQUE_DIGEST, im.CREATED_AT, im.UPDATED_AT
		FROM IMAGE_MANIFEST im 
		JOIN IMAGE_MANIFEST_TAG_MAPPING imtm  on imtm.MANIFEST_ID = im.ID
		JOIN IMAGE_TAG it ON it.ID = imtm.TAG_ID
		WHERE im.REPOSITORY_ID  = ? AND it.TAG = ?`

	GetRepositoryByNamesQuery = `SELECT rr.ID, rr.NAME, rr.DESCRIPTION, rr.IS_PUBLIC, rr.STATE, rr.NAMESPACE_ID,
	 rr.REGISTRY_ID, rr.CREATED_AT, rr.UPDATED_AT FROM REGISTRY_REPOSITORY rr
	JOIN REGISTRY_NAMESPACE ON rr.NAMESPACE_ID = rn.ID
	WHERE rn.NAME = ? AND rr.NAME = ?
	`
)

const (
	UpstreamCreateQuery      = `INSERT INTO UPSTREAM_REGISTRY(NAME, DESCRIPTION, VENDOR, STATE, PORT, UPSTREAM_URL) VALUES(?, ?, ?, ?, ?, ?) RETURNING ID`
	UpstreamUpdateQuery      = `UPDATE UPSTREAM_REGISTRY DESCRIPTION = ?, STATE = ?, PORT = ?, UPSTREAM_URL = ? WHERE REGISTRY_ID = ?`
	UpstreamDeleteQuery      = `DELETE FROM UPSTREAM_REGISTRY WHERE REGISTRY_ID = ?`
	UpstreamGetQuery         = `SELECT ID, NAME, DESCRIPTION, VENDOR, STATE, PORT, UPSTREAM_URL, CREATED_AT, UPDATED_AT WHERE REGISTRY_ID = ?`
	UpstreamChangeStateQuery = `UPDATE UPSTREAM_REGISTRY SET STATE = ? WHERE REGISTRY_ID = ?`

	UpstreamPersistAuthConfigQuery = `INSERT INTO UPSTREAM_REGISTRY_AUTH_CONFIG(AUTH_TYPE, CONFIG_JSON, REGISTRY_ID) VALUES (?, ?, ?)`
	UpstreamUpdateAuthConfigQuery  = `UPDATE UPSTREAM_REGISTRY_AUTH_CONFIG SET AUTH_TYPE = ?, CONFIG_JSON = ? WHERE REGISTRY_ID = ?`
	UpstreamGetAuthConfigQuery     = `SELECT AUTH_TYPE, CONFIG_JSON, CREATED_AT, UPDATED_AT FROM UPSTREAM_REGISTRY_AUTH_CONFIG WHERE REGISTRY_ID = ?`

	UpstreamPersistCacheConfigQuery = `INSERT INTO UPSTREAM_REGISTRY_CACHE_STORAGE_CONFIG(REGISTRY_ID, CACHE_ENABLED, TTL_SECONDS, STORAGE_LIMIT, CLEANUP_THRESHOLD_PERCENTAGE) VALUES(?, ?, ?, ?, ?)`
	UpstreamUpdateCacheConfigQuery  = `UPDATE UPSTREAM_REGISTRY_CACHE_STORAGE_CONFIG SET CACHE_ENABLED = ?, TTL_SECONDS = ?, STORAGE_LIMIT = ?, CLEANUP_THRESHOLD_PERCENTAGE = ? WHERE REGISTRY_ID = ?`
	UpstreamGetCacheConfigQuery     = `SELECT CACHE_ENABLED, TTL_SECONDS, STORAGE_LIMIT, CLEANUP_THRESHOLD_PERCENTAGE, CREATED_AT, UPDATED_AT FROM UPSTREAM_REGISTRY_CACHE_STORAGE_CONFIG WHERE REGISTRY_ID = ?`

	UpstreamPersistNetworkConfigQuery = `INSERT INTO UPSTREAM_REGISTRY_NETWORK_CONFIG(REGISTRY_ID, CONNECTION_TIMEOUT, READ_TIMEOUT, WRITE_TIMEOUT, MAX_CONNECTIONS, MAX_IDLE_CONNECTIONS, MAX_RETRIES, RETRY_DELAY, RETRY_BACKOFF_MULTIPLIER) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)`
	UpstreamUpdateNetworkConfigQuery  = `UPDATE UPSTREAM_REGISTRY_NETWORK_CONFIG SET CONNECTION_TIMEOUT = ? , READ_TIMEOUT = ? , WRITE_TIMEOUT = ? , MAX_CONNECTIONS = ? , MAX_IDLE_CONNECTIONS = ?, MAX_RETRIES = ?, RETRY_DELAY = ?, RETRY_BACKOFF_MULTIPLIER = ? WHERE REGISTRY_ID = ?`
	UpstreamGetNetworkConfigQuery     = `SELECT CONNECTION_TIMEOUT, READ_TIMEOUT, WRITE_TIMEOUT, MAX_CONNECTIONS, MAX_IDLE_CONNECTIONS, MAX_RETRIES, RETRY_DELAY, RETRY_BACKOFF_MULTIPLIER, CREATED_AT, UPDATED_AT FROM UPSTREAM_REGISTRY_NETWORK_CONFIG WHERE REGISTRY_ID = ?`

	UpstreamGetAllAddresses = `SELECT ID, NAME, PORT, UPSTREAM_URL FROM UPSTREAM_REGISTRY`
)