package db

const InsertUptreamOciRegistry = `INSERT INTO UPSTREAM_OCI_REGISTRY(NAME, PORT, UPSTREAM_URL) VALUES(?, ?, ?) RETURNING ID`

const UpdateUpstreamOciRegistry = `UPDATE UPSTREAM_OCI_REGISTRY SET NAME = ?, PORT = ?, UPSTREAM_URL = ? WHERE ID = ?`

const InsertUpstreamOciRegistryAuthConfig = `INSERT INTO UPSTREAM_OCI_REGISTRY_AUTH_CONFIG(REGISTRY_ID, AUTH_TYPE,
 CREDENTIAL_JSON, TOKEN_ENDPOINT, CERTIFICATE) VALUES(?, ?, ?, ?, ?)`

const UpdateUpstreamOciRegistryAuthConfig = `UPDATE UPSTREAM_OCI_REGISTRY_AUTH_CONFIG
 SET AUTH_TYPE = ?, CREDENTIAL_JSON = ?, TOKEN_ENDPOINT = ?, CERTIFICATE = ? WHERE REGISTRY_ID = ?`

const InsertUpstreamOciRegistryAccessConfig = `INSERT INTO UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG(REGISTRY_ID, PROXY_ENABLED,
	PROXY_URL, CONNECTION_TIMEOUT, READ_TIMEOUT, MAX_CONNECTIONS, MAX_RETRIES, RETRY_DELAY) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`

const UpdateUpstreamRegistryAccessConfig = `UPDATE UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG
	SET 
		PROXY_ENABLED = ?, 
		PROXY_URL = ?, 
		CONNECTION_TIMEOUT = ?, 
		READ_TIMEOUT = ?, 
		MAX_CONNECTIONS = ?, 
		MAX_RETRIES = ?, 
		RETRY_DELAY = ?
	WHERE REGISTRY_ID = ?`

const InsertUpstreamOciRegistryStorageConfig = `INSERT INTO UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG(REGISTRY_ID, STORAGE_LIMIT,
	CLEANUP_POLICY, CLEANUP_THRESHOLD_PERCENTAGE) VALUES (?, ?, ?, ?)`

const UpdateUpstreamOciRegistryStorageConfig = `UPDATE UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG
	SET 
		STORAGE_LIMIT = ?, 
		CLEANUP_POLICY = ?, 
		CLEANUP_THRESHOLD_PERCENTAGE = ?
	WHERE REGISTRY_ID = ?`

const InsertUpstreamOciRegistryCacheConfig = `INSERT INTO UPSTREAM_OCI_REGISTRY_CACHE_CONFIG(REGISTRY_ID, TTL_SECONDS,
	OFFLINE_MODE) VALUES (?, ?, ?)`

const UpdateUpstreamOciRegistryCacheConfig = `UPDATE UPSTREAM_OCI_REGISTRY_CACHE_CONFIG
	SET 
		TTL_SECONDS = ?, 
		OFFLINE_MODE = ?
	WHERE REGISTRY_ID = ?`

const DeleteUpstreamOciRegistry = `DELETE FROM UPSTREAM_OCI_REGISTRY WHERE ID = ?`

const GetUpstreamOciRegistry = `SELECT NAME, PORT, STATUS, UPSTREAM_URL, CREATED_AT, UPDATED_AT FROM UPSTREAM_OCI_REGISTRY WHERE ID = ?`

// TODO: join tables to get the actual cached image count
const GetListUpstreamOciRegisteriesWithAdditionalInfo = `SELECT ID, NAME, PORT, STATUS, UPSTREAM_URL, CREATED_AT, UPDATED_AT, 0 AS CACHED_IMAGE_COUNT FROM UPSTREAM_OCI_REGISTRY`

const GetUpstreamOCIRegistryWithConfig = `SELECT reg.NAME, reg.PORT, reg.UPSTREAM_URL, reg.CREATED_AT, reg.UPDATED_AT,
	auth.AUTH_TYPE, auth.CREDENTIAL_JSON, auth.TOKEN_ENDPOINT, auth.CERTIFICATE, auth.UPDATED_AT,
	access.PROXY_ENABLED, access.PROXY_URL, access.CONNECTION_TIMEOUT, access.READ_TIMEOUT,
	access.MAX_CONNECTIONS, access.MAX_RETRIES, access.RETRY_DELAY, access.UPDATED_AT,
	storage.STORAGE_LIMIT, storage.CLEANUP_POLICY, storage.CLEANUP_THRESHOLD_PERCENTAGE, storage.UPDATED_AT,
	cache.TTL_SECONDS, cache.OFFLINE_MODE, cache.UPDATED_AT
	FROM UPSTREAM_OCI_REGISTRY reg
	JOIN UPSTREAM_OCI_REGISTRY_AUTH_CONFIG auth ON reg.ID = auth.REGISTRY_ID
	JOIN UPSTREAM_OCI_REGISTRY_CACHE_CONFIG cache ON reg.ID = cache.REGISTRY_ID
	JOIN UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG storage ON reg.ID = storage.REGISTRY_ID
	JOIN UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG access ON reg.ID = access.REGISTRY_ID
	WHERE reg.ID = ?
`
