package db

// Upstream OCI Registry
const InsertUptreamOciRegistry = `INSERT INTO UPSTREAM_OCI_REGISTRY(NAME, PORT, UPSTREAM_URL) VALUES(?, ?, ?) RETURNING ID`
const UpdateUpstreamOciRegistry = `UPDATE UPSTREAM_OCI_REGISTRY SET NAME = ?, PORT = ?, UPSTREAM_URL = ? WHERE ID = ?`
const DeleteUpstreamOciRegistry = `DELETE FROM UPSTREAM_OCI_REGISTRY WHERE ID = ?`
const GetUpstreamOciRegistry = `SELECT NAME, PORT, STATUS, UPSTREAM_URL, CREATED_AT, UPDATED_AT FROM UPSTREAM_OCI_REGISTRY WHERE ID = ?`
const GetListUpstreamOciRegisteriesWithAdditionalInfo = `SELECT ID, NAME, PORT, STATUS, UPSTREAM_URL, CREATED_AT, UPDATED_AT, 0 AS CACHED_IMAGE_COUNT FROM UPSTREAM_OCI_REGISTRY`
const GetUpstreamOCIRegistryWithConfig = `SELECT reg.NAME, reg.PORT, reg.UPSTREAM_URL, reg.CREATED_AT, reg.UPDATED_AT,
	auth.AUTH_TYPE, auth.CREDENTIAL_JSON, auth.TOKEN_ENDPOINT, auth.CERTIFICATE, auth.UPDATED_AT,
	access.PROXY_ENABLED, access.PROXY_URL, access.CONNECTION_TIMEOUT, access.READ_TIMEOUT,
	access.MAX_CONNECTIONS, access.MAX_RETRIES, access.RETRY_DELAY, access.UPDATED_AT,
	storage.STORAGE_LIMIT, storage.CLEANUP_POLICY, storage.CLEANUP_THRESHOLD_PERCENTAGE, storage.UPDATED_AT,
	cache.TTL_SECONDS, cache.OFFLINE_MODE, cache.UPDATED_AT
	FROM UPSTREAM_OCI_REGISTRY reg
	JOIN UPSTREAM_OCI_REGISTRY_AUTH_CONFIG auth ON reg.ID = auth.REGISTRY_ID
	JOIN UPSTREAM_OCI_REGISTRY_CACHE_CONFIG cache ON reg.ID = cache.REGISTRY_ID
	JOIN UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG storage ON reg.ID = storage.REGISTRY_ID
	JOIN UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG access ON reg.ID = access.REGISTRY_ID
	WHERE reg.ID = ?`
const LoadActiveUpstreamRegistryAddressess = `SELECT ID, NAME, PORT, UPSTREAM_URL FROM UPSTREAM_OCI_REGISTRY WHERE STATUS = 'active'`

// Auth Config
const InsertUpstreamOciRegistryAuthConfig = `INSERT INTO UPSTREAM_OCI_REGISTRY_AUTH_CONFIG(REGISTRY_ID, AUTH_TYPE, CREDENTIAL_JSON, TOKEN_ENDPOINT, CERTIFICATE) VALUES(?, ?, ?, ?, ?)`
const UpdateUpstreamOciRegistryAuthConfig = `UPDATE UPSTREAM_OCI_REGISTRY_AUTH_CONFIG SET AUTH_TYPE = ?, CREDENTIAL_JSON = ?, TOKEN_ENDPOINT = ?, CERTIFICATE = ? WHERE REGISTRY_ID = ?`

// Access Config
const InsertUpstreamOciRegistryAccessConfig = `INSERT INTO UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG(REGISTRY_ID, PROXY_ENABLED, PROXY_URL, CONNECTION_TIMEOUT, READ_TIMEOUT, MAX_CONNECTIONS, MAX_RETRIES, RETRY_DELAY) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`
const UpdateUpstreamRegistryAccessConfig = `UPDATE UPSTREAM_OCI_REGISTRY_ACCESS_CONFIG SET PROXY_ENABLED = ?, PROXY_URL = ?, CONNECTION_TIMEOUT = ?, READ_TIMEOUT = ?, MAX_CONNECTIONS = ?, MAX_RETRIES = ?, RETRY_DELAY = ? WHERE REGISTRY_ID = ?`

// Storage Config
const InsertUpstreamOciRegistryStorageConfig = `INSERT INTO UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG(REGISTRY_ID, STORAGE_LIMIT, CLEANUP_POLICY, CLEANUP_THRESHOLD_PERCENTAGE) VALUES (?, ?, ?, ?)`
const UpdateUpstreamOciRegistryStorageConfig = `UPDATE UPSTREAM_OCI_REGISTRY_STORAGE_CONFIG SET STORAGE_LIMIT = ?, CLEANUP_POLICY = ?, CLEANUP_THRESHOLD_PERCENTAGE = ? WHERE REGISTRY_ID = ?`

// Cache Config
const InsertUpstreamOciRegistryCacheConfig = `INSERT INTO UPSTREAM_OCI_REGISTRY_CACHE_CONFIG(REGISTRY_ID, TTL_SECONDS, OFFLINE_MODE) VALUES (?, ?, ?)`
const UpdateUpstreamOciRegistryCacheConfig = `UPDATE UPSTREAM_OCI_REGISTRY_CACHE_CONFIG SET TTL_SECONDS = ?, OFFLINE_MODE = ? WHERE REGISTRY_ID = ?`

// Namespaces
const GetNamespaceIdByName = `SELECT ID FROM REGISTRY_NAMESPACE WHERE NAMESPACE = ? AND REGISTRY_ID = ?`
const InsertNewNamespace = `INSERT INTO REGISTRY_NAMESPACE(REGISTRY_ID, NAMESPACE) VALUES(?, ?)`
const InsertNamespace = `INSERT INTO REGISTRY_NAMESPACE(REGISTRY_ID, NAMESPACE) VALUES(?, ?) RETURNING ID`
const CheckNamespaceExists = `SELECT ID FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND NAMESPACE = ?`
const GetNamespaceID = `SELECT ID FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND NAMESPACE = ?`

// Repositories
const GetRepositoryIdByName = `SELECT ID FROM REGISTRY_REPOSITORY WHERE NAME = ? AND NAMESPACE_ID = ? AND REGISTRY_ID = ?`
const InsertNewRepository = `INSERT INTO REGISTRY_REPOSITORY(REGISTRY_ID, NAMESPACE_ID, NAME) VALUES (?, ?, ?)`
const InsertImageRepository = `INSERT INTO REGISTRY_REPOSITORY(REGISTRY_ID, NAMESPACE_ID, NAME) VALUES(?, ?, ?) RETURNING ID`
const CheckImageRepositoryExists = `SELECT ID FROM REGISTRY_REPOSITORY WHERE REGISTRY_ID = ? AND NAMESPACE_ID = ? AND NAME = ?`
const GetRepositoryID = `SELECT ID FROM REGISTRY_REPOSITORY WHERE REGISTRY_ID = ? AND NAMESPACE_ID = ? AND NAME = ?`

// Blob Meta
const PersistImageBlobMeta = `INSERT INTO IMAGE_BLOB_META(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, BLOB_DIGEST, MEDIA_TYPE, SIZE, STORAGE_LOCATION) VALUES(?, ?, ?, ?, ?, ?, ?)`
const CheckImageBlobExistense = `SELECT 1 FROM IMAGE_BLOB_META ibm JOIN REGISTRY_NAMESPACE rn ON rn.ID = ibm.NAMESPACE_ID JOIN REGISTRY_REPOSITORY rr ON rr.ID = ibm.REPOSITORY_ID WHERE ibm.REGISTRY_ID = ? AND rn.NAMESPACE = ? AND rr.NAME = ? AND ibm.BLOB_DIGEST = ?`
const GetImageBlobStorageLocationAndSize = `SELECT STORAGE_LOCATION, SIZE FROM IMAGE_BLOB_META ibm JOIN REGISTRY_NAMESPACE rn ON rn.ID = ibm.NAMESPACE_ID JOIN REGISTRY_REPOSITORY rr ON rr.ID = ibm.REPOSITORY_ID WHERE ibm.REGISTRY_ID = ? AND rn.NAMESPACE = ? AND rr.NAME = ? AND ibm.BLOB_DIGEST = ?`
const GetImageBlobStorageLocationAndSizeByIds = `SELECT STORAGE_LOCATION, SIZE FROM IMAGE_BLOB_META WHERE REGISTRY_ID = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND BLOB_DIGEST = ?`
const UpdateImageBlobMediaType = `UPDATE IMAGE_BLOB_META SET MEDIA_TYPE = ? WHERE REGISTRY_ID = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND BLOB_DIGEST = ?`
const CheckImageBlobExistsByIds = `SELECT 1 FROM IMAGE_BLOB_META WHERE REGISTRY_ID = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND BLOB_DIGEST = ?`

// Blob Upload Session
const PersistImageBlobUploadSession = `INSERT INTO IMAGE_BLOB_UPLOAD_SESSION(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, SESSION_ID, BLOB_DIGEST, IS_CHUNKED) VALUES(?, ?, ?, ?, ?, ?)`
const GetBlobUploadSession = `SELECT SESSION_ID, IS_CHUNKED, UPDATED_AT FROM IMAGE_BLOB_UPLOAD_SESSION WHERE SESSION_ID = ?`
const GetImageBlobUploadSession = `SELECT IS_CHUNKED, UPDATED_AT FROM IMAGE_BLOB_UPLOAD_SESSION WHERE SESSION_ID = ?`
const MarkBlobUploadSessionAsChunked = `UPDATE IMAGE_BLOB_UPLOAD_SESSION SET IS_CHUNKED  = 1 WHERE SESSION_ID = ?`
const DeleteBlobUploadSession = `DELETE FROM IMAGE_BLOB_UPLOAD_SESSION WHERE SESSION_ID = ?`

// Manifests
const PersistImageManifest = `INSERT INTO IMAGE_MANIFEST(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, DIGEST, IMAGE_CONFIG_DIGEST, MEDIA_TYPE, SIZE, MANIFEST_CONTENT, UNIQUE_DIGEST) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)`
const GetImageManifestByDigest = `SELECT MANIFEST_CONTENT, MEDIA_TYPE, SIZE FROM IMAGE_MANIFEST im JOIN REGISTRY_REPOSITORY rr ON im.REPOSITORY_ID = rr.ID JOIN REGISTRY_NAMESPACE rn ON im.NAMESPACE_ID = rn.ID WHERE im.REGISTRY_ID = ? AND rn.NAMESPACE = ? AND rr.NAME = ? AND im.DIGEST = ?`
const CheckImageManifestExistense = `SELECT 1 FROM IMAGE_MANIFEST im JOIN REGISTRY_NAMESPACE rn ON rn.ID = im.NAMESPACE_ID JOIN REGISTRY_REPOSITORY rr ON rr.ID = im.REPOSITORY_ID WHERE im.UNIQUE_DIGEST = ? AND im.REGISTRY_ID = ? AND rn.NAMESPACE = ? AND rr.NAME = ?`

// Platform Config
const PersistImagePlatformConfig = `INSERT INTO IMAGE_PLATFORM_CONFIG(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, TAG_ID, CONFIG_DIGEST, OS, ARCH, PROPERTIES) VALUES(?, ?, ?, ?, ?, ?, ?, ?)`
const CheckImagePlatformConfigExistence = `SELECT 1 FROM IMAGE_PLATFORM_CONFIG WHERE TAG_ID = ? AND CONFIG_DIGEST = ?`

// Tags
const PersistImageTag = `INSERT INTO IMAGE_TAG(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, TAG) VALUES(?, ?, ?, ?) RETURNING ID`
const GetImageTagId = `SELECT ID FROM IMAGE_TAG WHERE REGISTRY_ID = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND TAG = ?`

// Tag Config Mapping
const LinkImageConfigDigestWithImageTag = `INSERT INTO IMAGE_TAG_CONFIG_MAPPING(TAG_ID, CONFIG_DIGEST) VALUES(?, ?)`
const CheckImageTagConfigMapping = `SELECT 1 FROM IMAGE_TAG_CONFIG_MAPPING WHERE TAG_ID = ? AND CONFIG_DIGEST = ?`

// Layer Tag Mapping
const InsertImageTagLayerMapping = `INSERT INTO IMAGE_LAYER_TAG_MAPPING(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, TAG_ID, LAYER_DIGEST, IMAGE_CONFIG_DIGEST, LAYER_INDEX) VALUES(?, ?, ?, ?, ?, ?, ?)`
const CheckImageTagLayerMappingExistence = `SELECT 1 FROM IMAGE_LAYER_TAG_MAPPING WHERE TAG_ID = ? AND LAYER_DIGEST = ? AND LAYER_INDEX = ?`

// TODO / Fix later
const CheckImageManifestExistenseByTag = `
SELECT 1 FROM IMAGE_MANIFEST im
	JOIN REGISTRY_NAMESPACE rn ON rn.ID = im.NAMESPACE_ID
	JOIN REGISTRY_REPOSITORY rr ON rr.ID = im.REPOSITORY_ID
	JOIN IMAGE_TAG it ON it.ID = im.TAG_ID
	WHERE im.REGISTRY_ID = ? AND it.TAG = ? AND rn.NAMESPACE = ? AND rr.NAME = ?`

const GetImageManifestsWithPlatformByTag = `
SELECT im.MEDIA_TYPE, im.DIGEST, im.SIZE, ipc.OS, ipc.ARCH  
FROM IMAGE_MANIFEST im
	JOIN REGISTRY_NAMESPACE rn ON rn.ID = im.NAMESPACE_ID
	JOIN REGISTRY_REPOSITORY rr ON rr.ID = im.REPOSITORY_ID
	JOIN IMAGE_TAG it ON it.ID = im.TAG_ID
	JOIN IMAGE_PLATFORM_CONFIG ipc ON ipc.CONFIG_DIGEST = im.IMAGE_CONFIG_DIGEST
	WHERE im.REGISTRY_ID = ? AND it.TAG = ? AND rn.NAMESPACE = ? AND rr.NAME = ?`

const GetImageManifestsWithPlatformByDigest = `
SELECT im.MEDIA_TYPE, im.SIZE, im.MANIFEST_CONTENT  
FROM IMAGE_MANIFEST im
	JOIN REGISTRY_NAMESPACE rn ON rn.ID = im.NAMESPACE_ID
	JOIN REGISTRY_REPOSITORY rr ON rr.ID = im.REPOSITORY_ID
	WHERE im.REGISTRY_ID = ? AND rn.NAMESPACE = ? AND rr.NAME = ?`

const GetImageManifestsExistByTagWithPlatformAttributes = `SELECT ipc.OS, ipc.ARCH, im.DIGEST, im.SIZE, im.MEDIA_TYPE FROM IMAGE_MANIFEST im
 JOIN IMAGE_TAG_CONFIG_MAPPING itcm ON im.IMAGE_CONFIG_DIGEST = itcm.CONFIG_DIGEST
 JOIN IMAGE_PLATFORM_CONFIG ipc ON ipc.CONFIG_DIGEST = im.IMAGE_CONFIG_DIGEST
 JOIN IMAGE_TAG it ON it.ID = itcm.TAG_ID
 JOIN REGISTRY_REPOSITORY rr ON im.REPOSITORY_ID = rr.ID
 JOIN REGISTRY_NAMESPACE rn ON im.NAMESPACE_ID = rn.ID
 WHERE im.REGISTRY_ID = ? AND rn.NAMESPACE = ? AND rr.NAME = ? AND it.TAG = ?`

const CheckImageManifestsExistByTag = `SELECT 1 FROM IMAGE_MANIFEST im
 JOIN IMAGE_TAG_CONFIG_MAPPING itcm ON im.IMAGE_CONFIG_DIGEST = itcm.CONFIG_DIGEST
 JOIN IMAGE_TAG it ON it.ID = itcm.TAG_ID
 JOIN REGISTRY_REPOSITORY rr ON im.REPOSITORY_ID = rr.ID
 JOIN REGISTRY_NAMESPACE rn ON im.NAMESPACE_ID = rn.ID
 WHERE im.REGISTRY_ID = ? AND rn.NAMESPACE = ? AND rr.NAME = ? AND it.TAG = ?`
