package db

const (
	InsertUptreamRegistry               = `INSERT INTO UPSTREAM_REGISTRY(NAME, PORT, STATUS, UPSTREAM_URL) VALUES(?, ?, ?, ?) RETURNING ID`
	InsertUpstreamRegistryAuthConfig    = `INSERT INTO UPSTREAM_REGISTRY_AUTH_CONFIG(REGISTRY_ID, AUTH_TYPE, CREDENTIAL_JSON, TOKEN_ENDPOINT) VALUES(?, ?, ?, ?)`
	InsertUpstreamRegistryStorageConfig = `INSERT INTO UPSTREAM_REGISTRY_STORAGE_CONFIG(REGISTRY_ID, STORAGE_LIMIT, CLEANUP_POLICY, CLEANUP_THRESHOLD_PERCENTAGE) VALUES(?, ?, ?, ?)`
	InsertUpstreamRegistryCacheConfig   = `INSERT INTO UPSTREAM_REGISTRY_CACHE_CONFIG(REGISTRY_ID, ENABLED, TTL_SECONDS, OFFLINE_MODE) VALUES(?, ?, ?, ?)`
	InsertUpstreamRegistryAccessConfig  = `INSERT INTO UPSTREAM_REGISTRY_ACCESS_CONFIG(REGISTRY_ID, PROXY_ENABLED, PROXY_URL, CONNECTION_TIMEOUT, READ_TIMEOUT, MAX_CONNECTIONS, MAX_RETRIES, RETRY_DELAY) VALUES(?, ?, ?, ?, ?, ?, ?, ?)`
	UpdateUpstreamRegistry              = `UPDATE UPSTREAM_REGISTRY SET NAME = ?,  PORT = ?, STATUS = ?, UPSTREAM_URL = ? WHERE ID = ? RETURNING ID`
	UpdateUpstreamRegistryAuthConfig    = `UPDATE UPSTREAM_REGISTRY_AUTH_CONFIG SET AUTH_TYPE = ?, CREDENTIAL_JSON = ?, TOKEN_ENDPOINT = ? WHERE REGISTRY_ID = ?`
	UpdateUpstreamRegistryCacheConfig   = `UPDATE UPSTREAM_REGISTRY_CACHE_CONFIG SET ENABLED = ?, TTL_SECONDS = ?, OFFLINE_MODE = ? WHERE REGISTRY_ID = ?`
	UpdateUpstreamRegistryStorageConfig = `UPDATE UPSTREAM_REGISTRY_STORAGE_CONFIG SET STORAGE_LIMIT = ?, CLEANUP_POLICY = ?, CLEANUP_THRESHOLD_PERCENTAGE = ? WHERE REGISTRY_ID = ?`
	UpdateUpstreamRegistryAccessConfig  = `UPDATE UPSTREAM_REGISTRY_ACCESS_CONFIG SET PROXY_ENABLED = ?, PROXY_URL = ?, CONNECTION_TIMEOUT = ?, READ_TIMEOUT = ?, MAX_CONNECTIONS = ?, MAX_RETRIES = ?, RETRY_DELAY = ? WHERE REGISTRY_ID = ?`
	DeleteUpstreamRegistry              = `DELETE FROM UPSTREAM_REGISTRY WHERE ID = ?`
	DeleteUpstreamRegistryAuthConfig    = `DELETE FROM UPSTREAM_REGISTRY_AUTH_CONFIG WHERE REGISTRY_ID = ?`
	DeleteUpstreamRegistryCacheConfig   = `DELETE FROM UPSTREAM_REGISTRY_CACHE_CONFIG WHERE REGISTRY_ID = ?`
	DeleteUpstreamRegistryStorageConfig = `DELETE FROM UPSTREAM_REGISTRY_STORAGE_CONFIG WHERE REGISTRY_ID = ?`
	DeleteUpstreamRegistryAccessConfig  = `DELETE FROM UPSTREAM_REGISTRY_ACCESS_CONFIG WHERE REGISTRY_ID = ?`
	GetUpstreamRegistryWithConfig       = `SELECT reg.NAME, reg.PORT, reg.UPSTREAM_URL, reg.CREATED_AT, reg.UPDATED_AT,
		auth.AUTH_TYPE, auth.CREDENTIAL_JSON, auth.TOKEN_ENDPOINT, auth.UPDATED_AT,
		access.PROXY_ENABLED, access.PROXY_URL, access.CONNECTION_TIMEOUT, access.READ_TIMEOUT,
		access.MAX_CONNECTIONS, access.MAX_RETRIES, access.RETRY_DELAY, access.UPDATED_AT,
		storage.STORAGE_LIMIT, storage.CLEANUP_POLICY, storage.CLEANUP_THRESHOLD_PERCENTAGE, storage.UPDATED_AT,
		cache.TTL_SECONDS, cache.OFFLINE_MODE, cache.UPDATED_AT
	FROM UPSTREAM_REGISTRY reg
	JOIN UPSTREAM_REGISTRY_AUTH_CONFIG auth ON reg.ID = auth.REGISTRY_ID
	JOIN UPSTREAM_REGISTRY_CACHE_CONFIG cache ON reg.ID = cache.REGISTRY_ID
	JOIN UPSTREAM_REGISTRY_STORAGE_CONFIG storage ON reg.ID = storage.REGISTRY_ID
	JOIN UPSTREAM_REGISTRY_ACCESS_CONFIG access ON reg.ID = access.REGISTRY_ID
	WHERE reg.ID = ?`
	ListUpstreamRegistrySummary = `SELECT ID, NAME, PORT, STATUS, UPSTREAM_URL, CREATED_AT, UPDATED_AT, 0 AS CACHED_IMAGE_COUNT FROM UPSTREAM_REGISTRY`
	GetActiveUpstreamAddresses  = `SELECT ID, NAME, PORT, UPSTREAM_URL FROM UPSTREAM_REGISTRY WHERE STATUS = 'active'`
)

// Namespace
const (
	InsertNamespace      = `INSERT INTO REGISTRY_NAMESPACE(REGISTRY_ID, NAMESPACE) VALUES(?, ?) RETURNING ID`
	GetNamespaceIdByName = `SELECT ID FROM REGISTRY_NAMESPACE WHERE REGISTRY_ID = ? AND NAMESPACE = ?`
)

// Repository
const (
	InsertImageRepository = `INSERT INTO REGISTRY_REPOSITORY(REGISTRY_ID, NAMESPACE_ID, NAME) VALUES(?, ?, ?) RETURNING ID`
	GetRepositoryIdByName = `SELECT ID FROM REGISTRY_REPOSITORY WHERE REGISTRY_ID = ? AND NAMESPACE_ID = ? AND NAME = ?`
)

// ImageBlobMeta
const (
	InsertImageBlobMetaInfo     = `INSERT INTO IMAGE_BLOB_META(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, BLOB_DIGEST, SIZE, STORAGE_LOCATION) VALUES(?, ?, ?, ?, ?, ?)`
	GetImageBlobLocationAndSize = `SELECT STORAGE_LOCATION, SIZE FROM IMAGE_BLOB_META ibm JOIN REGISTRY_NAMESPACE rn ON rn.ID = ibm.NAMESPACE_ID JOIN REGISTRY_REPOSITORY rr ON rr.ID = ibm.REPOSITORY_ID WHERE ibm.REGISTRY_ID = ? AND rn.NAMESPACE = ? AND rr.NAME = ? AND ibm.BLOB_DIGEST = ?`
)

// ImageTag
const (
	InsertImageTag = `INSERT INTO IMAGE_TAG(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, TAG) VALUES(?, ?, ?, ?) RETURNING ID`
	GetImageTagId  = `SELECT ID FROM IMAGE_TAG WHERE REGISTRY_ID = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND TAG = ?`
)

// ImageManifest
const (
	InsertImageManifest   = `INSERT INTO IMAGE_MANIFEST(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, DIGEST, MEDIA_TYPE, SIZE, MANIFEST_CONTENT, UNIQUE_DIGEST) VALUES(?, ?, ?, ?, ?, ?, ?, ?) RETURNING ID`
	GetImageManifestByTag = `SELECT im.DIGEST, im.MEDIA_TYPE, im.MANIFEST_CONTENT
		FROM IMAGE_MANIFEST im 
		JOIN IMAGE_MANIFEST_TAG_MAPPING imtm  on imtm.MANIFEST_ID = im.ID
		JOIN IMAGE_TAG it ON it.ID = imtm.TAG_ID
		WHERE im.REGISTRY_ID  = ? AND im.NAMESPACE_ID = ? AND im.REPOSITORY_ID  = ? AND it.TAG = ?`
	CheckImageManifestByTag = `SELECT im.DIGEST, im.MEDIA_TYPE
		FROM IMAGE_MANIFEST im 
		JOIN IMAGE_MANIFEST_TAG_MAPPING imtm  on imtm.MANIFEST_ID = im.ID
		JOIN IMAGE_TAG it ON it.ID = imtm.TAG_ID
		WHERE im.REGISTRY_ID  = ? AND im.NAMESPACE_ID = ? AND im.REPOSITORY_ID  = ? AND it.TAG = ?`
	CheckImageManifestByDigest = `SELECT MEDIA_TYPE FROM IMAGE_MANIFEST WHERE REGISTRY_ID  = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND DIGEST = ?`
	GetImageManifestByDigest   = `SELECT MEDIA_TYPE, MANIFEST_CONTENT FROM IMAGE_MANIFEST WHERE REGISTRY_ID  = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND DIGEST = ?`

	CheckImageManifestByUniqueDigest = `SELECT ID FROM IMAGE_MANIFEST WHERE REGISTRY_ID  = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND UNIQUE_DIGEST = ?`
)

// image-registry-cache
const (
	InsertIntoImageRegistryCache      = `INSERT INTO IMAGE_REGISTRY_CACHE(REGISTRY_ID, NAMESPACE_ID, REPOSITORY_ID, IDENTIFIER, DIGEST, EXPIRES_AT) VALUES(?, ?, ?, ?, ?, ?)`
	DeleteEntryFromImageRegistryCache = `DELETE FROM IMAGE_REGISTRY_CACHE WHERE REGISTRY_ID  = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND IDENTIFIER = ?`
	GetEntryFromImageRegistryCache    = `SELECT DIGEST, EXPIRES_AT FROM IMAGE_REGISTRY_CACHE WHERE REGISTRY_ID  = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND IDENTIFIER = ?`
	RefreshImageRegistryCacheEntry    = `UPDATE IMAGE_REGISTRY_CACHE SET EXPIRES_AT  = ? WHERE REGISTRY_ID  = ? AND NAMESPACE_ID = ? AND REPOSITORY_ID = ? AND IDENTIFIER = ?`
)

// image-manifest-tag-mapping
const (
	InsertImageManifestTagMapping                 = `INSERT INTO IMAGE_MANIFEST_TAG_MAPPING(MANIFEST_ID, TAG_ID) VALUES(?, ?)`
	UpdateImageManifestTagMappingWitNewManifestId = `UPDATE IMAGE_MANIFEST_TAG_MAPPING SET MANIFEST_ID = ? WHERE TAG_ID = ?`
	GetManifestIdByTagId                          = `SELECT MANIFEST_ID FROM IMAGE_MANIFEST_TAG_MAPPING WHERE TAG_ID = ?`
)

// UserAccount
const (
	CountTotalUsers     = `SELECT COUNT(*) FROM USER_ACCOUNT`
	CountUsersBaseQuery = `SELECT COUNT(*)
	FROM USER_ACCOUNT acc
	LEFT JOIN USER_PASSWORD_RECOVERY pwr ON acc.ID = pwr.USER_ID
	LEFT JOIN USER_ROLE_ASSIGNMENT ra ON acc.ID = ra.USER_ID
	LEFT JOIN OAUTH_AUTH_SESSION session ON acc.ID = session.USER_ID
	WHERE acc.DELETED = 0
	`

	ListUsersBaseQuery = `SELECT acc.ID,
       acc.USERNAME,
       acc.EMAIL,
       acc.DISPLAY_NAME,
       acc.LOCKED,
       acc.LOCKED_REASON,
       acc.LOCKED_AT,
       acc.FAILED_ATTEMPTS,
       acc.CREATED_AT,
       acc.UPDATED_AT,
       ra.ROLE_NAME,
       pwr.RECOVERY_UUID,
       pwr.REASON_TYPE,
       pwr.CREATED_AT AS PW_RECOVERY_AT,
			 session.LAST_ACCESSED_AT
	FROM USER_ACCOUNT acc
	LEFT JOIN USER_PASSWORD_RECOVERY pwr ON acc.ID = pwr.USER_ID
	LEFT JOIN USER_ROLE_ASSIGNMENT ra ON acc.ID = ra.USER_ID
	LEFT JOIN OAUTH_AUTH_SESSION session ON acc.ID = session.USER_ID
	WHERE acc.DELETED = 0
`
	GetUserAccount = `SELECT ID, USERNAME, EMAIL, DISPLAY_NAME, LOCKED, FAILED_ATTEMPTS, CREATED_AT, UPDATED_AT
		FROM USER_ACCOUNT
		WHERE DELETED = 0 AND USERNAME = ?
	`
	GetUserAccountById = `SELECT ID, USERNAME, EMAIL, DISPLAY_NAME, LOCKED, LOCKED_REASON, FAILED_ATTEMPTS, CREATED_AT, UPDATED_AT, LOCKED_AT
		FROM USER_ACCOUNT
		WHERE DELETED = 0 AND ID = ?
	`
	GetUsernameById        = `SELECT USERNAME FROM USER_ACCOUNT WHERE DELETED = 0 AND ID = ?`
	GetUserPasswordAndSalt = `SELECT PASSWORD, SALT FROM USER_ACCOUNT WHERE DELETED = 0 AND ID = ?`

	MarkUserAccountAsDeleted = `UPDATE USER_ACCOUNT SET DELETED = 1, USERNAME = '[DELETED]' || USERNAME, EMAIL = '[DELETED]' || EMAIL, PASSWORD = '[DELETED]', SALT = '[DELETED]' WHERE ID = ?`
	InsertUserAccount        = `INSERT INTO USER_ACCOUNT(USERNAME, EMAIL, DISPLAY_NAME, PASSWORD, SALT) VALUES(?, ?, ?, ?, ?) RETURNING ID`
	LockUserAccount          = `UPDATE USER_ACCOUNT SET LOCKED = 1, LOCKED_REASON  = ?, LOCKED_AT = CURRENT_TIMESTAMP   WHERE USERNAME = ?`
	UnlockUserAccount        = `UPDATE USER_ACCOUNT SET LOCKED = 0, LOCKED_REASON = 0, LOCKED_AT = NULL WHERE USERNAME = ?`
	LockUserAccountById      = `UPDATE USER_ACCOUNT SET LOCKED = 1, LOCKED_REASON  = ?, LOCKED_AT = CURRENT_TIMESTAMP   WHERE ID = ?`
	UnlockUserAccountById    = `UPDATE USER_ACCOUNT SET LOCKED = 0, LOCKED_REASON = 0, LOCKED_AT = NULL WHERE ID = ?`
	UpdateFailedAttempts     = `UPDATE USER_ACCOUNT SET FAILED_ATTEMPTS = FAILED_ATTEMPTS + 1  WHERE USERNAME = ?`
	UpdatePassword           = `UPDATE USER_ACCOUNT SET PASSWORD = ?, SALT = ? WHERE ID = ?`
	UpdateUserEmail          = `UPDATE USER_ACCOUNT SET EMAIL = ? WHERE ID = ?`
	UpdateUserDisplayName    = `UPDATE USER_ACCOUNT SET DISPLAY_NAME = ? WHERE ID = ?`

	ValidateUsernameAndEmail = `SELECT acc.USERNAME, acc.EMAIL FROM USER_ACCOUNT acc WHERE USERNAME = ? OR EMAIL = ?`
	UpdateUserAccount        = `UPDATE USER_ACCOUNT SET EMAIL = ?, DISPLAY_NAME = ? WHERE ID = ?`
)

// password-recovery
const (
	PersistPasswordRecoveryRecord  = `INSERT INTO USER_PASSWORD_RECOVERY(RECOVERY_UUID, USER_ID, REASON_TYPE) VALUES(?, ?, ?)`
	GetPasswordRecoveryByUserId    = `SELECT USER_ID, RECOVERY_UUID, REASON_TYPE, CREATED_AT FROM  USER_PASSWORD_RECOVERY WHERE USER_ID = ?`
	GetPasswordRecoveryById        = `SELECT USER_ID, REASON_TYPE, CREATED_AT FROM  USER_PASSWORD_RECOVERY WHERE RECOVERY_UUID = ?`
	DeletePasswordRecoveryByUserId = `DELETE FROM USER_PASSWORD_RECOVERY WHERE USER_ID = ?`
)

// user-role
const (
	PersistUserRole    = `INSERT INTO USER_ROLE(NAME) VALUES(?)`
	DeleteUserRole     = `DELETE FROM USER_ROLE WHERE NAME = ?`
	CheckRoleExistence = `SELECT 1 FROM USER_ROLE WHERE NAME = ?`
)

// user-role-assignment
const (
	AssignRoleToUser = `INSERT INTO USER_ROLE_ASSIGNMENT(USER_ID, ROLE_NAME) VALUES(?, ?)`
	UnassignRole     = `DELETE FROM USER_ROLE_ASSIGNMENT WHERE USER_ID = ?`
	HasRole          = `SELECT 1 FROM USER_ROLE_ASSIGNMENT WHERE USER_ID = ? AND ROLE_NAME = ?`
	GetUserRole      = `SELECT ROLE_NAME FROM USER_ROLE_ASSIGNMENT WHERE USER_ID = ?`
)

// resource-access
const (
	GrantResourceAccess        = `INSERT INTO RESOURCE_ACCESS(RESOURCE_ID, USER_ID, ACCESS_LEVEL, RESOURCE_TYPE, GRANTED_BY) VALUES(?, ?, ?, ?, ?)`
	RevokeResourceAccess       = `DELETE FROM RESOURCE_ACCESS WHERE RESOURCE_ID = ? AND USER_ID = ? AND RESOURCE_TYPE = ?`
	GetUserResourceAccess      = `SELECT ID, RESOURCE_TYPE, RESOURCE_ID, USER_ID, ACCESS_LEVEL, GRANTED_BY, CREATED_AT, UPDATED_AT FROM RESOURCE_ACCESS WHERE USER_ID = ? AND RESOURCE_TYPE = ?`
	GetNamespaceAccessByUserId = `SELECT ra.ID, rn.NAMESPACE, ra.RESOURCE_ID, ra.USER_ID, ra.ACCESS_LEVEL, ra.GRANTED_BY, ra.CREATED_AT, ra.UPDATED_AT
	 FROM RESOURCE_ACCESS ra
	 JOIN USER_ACCOUNT ua ON ra.USER_ID = ua.ID
	 JOIN REGISTRY_NAMESPACE rn ON ra.RESOURCE_ID = rn.ID
	 WHERE ra.USER_ID = ? AND ra.RESOURCE_TYPE = 'namespace'
	`
	GetRepositoryAccessByUserId = `SELECT ra.ID, rn.NAMESPACE, rr.NAME, ra.RESOURCE_ID, ra.USER_ID, ra.ACCESS_LEVEL, ra.GRANTED_BY, ra.CREATED_AT, ra.UPDATED_AT
	 FROM RESOURCE_ACCESS ra
	 JOIN USER_ACCOUNT ua ON ra.USER_ID = ua.ID
	 JOIN REGISTRY_REPOSITORY rr ON ra.RESOURCE_ID = rr.ID
	 JOIN REGISTRY_NAMESPACE rn ON rr.NAMESPACE_ID = rn.ID
	 WHERE ra.USER_ID = ? AND ra.RESOURCE_TYPE = 'repository'`
)

// oauth-scope
const (
	PersistOauthScope = `INSERT INTO OAUTH_SCOPE(SCOPE_NAME, DESCRIPTION) VALUES(?, ?)`
)

// oauth-scope-role-binding
const (
	PersistOauthScopeRoleBinding = `INSERT INTO OAUTH_SCOPE_ROLE_BINDING(SCOPE_NAME, ROLE_NAME) VALUES(?, ?)`
	GetAllScopeRoleBindings      = `SELECT SCOPE_NAME, ROLE_NAME FROM OAUTH_SCOPE_ROLE_BINDING`
)

// oauth-sesssion
const (
	PersistOauthSession                 = `INSERT INTO OAUTH_AUTH_SESSION(SESSION_ID, USER_ID, SCOPE_HASH_SHA256, ISSUED_AT, EXPIRES_AT, USER_AGENT, IP_ADDRESS, GRANT_TYPE) VALUES(?, ?, ?, ?, ?, ?, ?, ?)`
	RemoveOauthSession                  = `DELETE FROM OAUTH_AUTH_SESSION WHERE SESSION_ID = ?`
	UpdateSessionLastAccess             = `UPDATE OAUTH_AUTH_SESSION SET LAST_ACCESSED_AT = ? WHERE SESSION_ID = ?`
	GetOauthSessionByScopeHashAndUserId = `SELECT SESSION_ID, ISSUED_AT, EXPIRES_AT, USER_AGENT, IP_ADDRESS, GRANT_TYPE, LAST_ACCESSED_AT FROM OAUTH_AUTH_SESSION WHERE SCOPE_HASH_SHA256 = ? AND USER_ID = ?`
)

// oauth-session-scope
const (
	PersistOauthSessionScope = `INSERT INTO OAUTH_AUTH_SESSION_SCOPE(SESSION_ID, SCOPE) VALUES(?, ?)`
)
